// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_alb_listener

import "github.com/golingon/lingon/pkg/terra"

var _ terra.DataSource = (*DataSource)(nil)

/*
DataSource is the data source aws_alb_listener.

Documentation: https://registry.terraform.io/providers/hashicorp/aws/5.0.0/docs
*/
type DataSource struct {
	Name string
	Args DataArgs
}

// DataSource returns the Terraform object type for [DataSource].
func (aal *DataSource) DataSource() string {
	return "aws_alb_listener"
}

// LocalName returns the local name for [DataSource].
func (aal *DataSource) LocalName() string {
	return aal.Name
}

// Configuration returns the configuration (args) for [DataSource].
func (aal *DataSource) Configuration() interface{} {
	return aal.Args
}

// Attributes returns the attributes for [DataSource].
func (aal *DataSource) Attributes() dataAwsAlbListenerAttributes {
	return dataAwsAlbListenerAttributes{ref: terra.ReferenceDataSource(aal)}
}

// DataArgs contains the configurations for aws_alb_listener.
type DataArgs struct {
	// Arn is optional.
	Arn terra.StringValue `hcl:"arn,attr"`
	// Id is optional.
	Id terra.StringValue `hcl:"id,attr"`
	// LoadBalancerArn is optional.
	LoadBalancerArn terra.StringValue `hcl:"load_balancer_arn,attr"`
	// Port is optional.
	Port terra.NumberValue `hcl:"port,attr"`
	// Tags is optional.
	Tags terra.MapValue[terra.StringValue] `hcl:"tags,attr"`
	// Timeouts is optional.
	Timeouts *DataTimeouts `hcl:"timeouts,block"`
}

type dataAwsAlbListenerAttributes struct {
	ref terra.Reference
}

// AlpnPolicy returns a reference to field alpn_policy of aws_alb_listener.
func (aal dataAwsAlbListenerAttributes) AlpnPolicy() terra.StringValue {
	return terra.ReferenceAsString(aal.ref.Append("alpn_policy"))
}

// Arn returns a reference to field arn of aws_alb_listener.
func (aal dataAwsAlbListenerAttributes) Arn() terra.StringValue {
	return terra.ReferenceAsString(aal.ref.Append("arn"))
}

// CertificateArn returns a reference to field certificate_arn of aws_alb_listener.
func (aal dataAwsAlbListenerAttributes) CertificateArn() terra.StringValue {
	return terra.ReferenceAsString(aal.ref.Append("certificate_arn"))
}

// Id returns a reference to field id of aws_alb_listener.
func (aal dataAwsAlbListenerAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(aal.ref.Append("id"))
}

// LoadBalancerArn returns a reference to field load_balancer_arn of aws_alb_listener.
func (aal dataAwsAlbListenerAttributes) LoadBalancerArn() terra.StringValue {
	return terra.ReferenceAsString(aal.ref.Append("load_balancer_arn"))
}

// Port returns a reference to field port of aws_alb_listener.
func (aal dataAwsAlbListenerAttributes) Port() terra.NumberValue {
	return terra.ReferenceAsNumber(aal.ref.Append("port"))
}

// Protocol returns a reference to field protocol of aws_alb_listener.
func (aal dataAwsAlbListenerAttributes) Protocol() terra.StringValue {
	return terra.ReferenceAsString(aal.ref.Append("protocol"))
}

// SslPolicy returns a reference to field ssl_policy of aws_alb_listener.
func (aal dataAwsAlbListenerAttributes) SslPolicy() terra.StringValue {
	return terra.ReferenceAsString(aal.ref.Append("ssl_policy"))
}

// Tags returns a reference to field tags of aws_alb_listener.
func (aal dataAwsAlbListenerAttributes) Tags() terra.MapValue[terra.StringValue] {
	return terra.ReferenceAsMap[terra.StringValue](aal.ref.Append("tags"))
}

func (aal dataAwsAlbListenerAttributes) DefaultAction() terra.ListValue[DatadefaultActionAttributes] {
	return terra.ReferenceAsList[DatadefaultActionAttributes](aal.ref.Append("default_action"))
}

func (aal dataAwsAlbListenerAttributes) Timeouts() DatatimeoutsAttributes {
	return terra.ReferenceAsSingle[DatatimeoutsAttributes](aal.ref.Append("timeouts"))
}
