// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_config_delivery_channel

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type SnapshotDeliveryProperties struct {
	// DeliveryFrequency is optional.
	DeliveryFrequency terra.StringValue `hcl:"delivery_frequency,attr"`
}

type snapshotDeliveryPropertiesAttributes struct {
	ref terra.Reference
}

func (sdp snapshotDeliveryPropertiesAttributes) InternalRef() (terra.Reference, error) {
	return sdp.ref, nil
}

func (sdp snapshotDeliveryPropertiesAttributes) InternalWithRef(ref terra.Reference) snapshotDeliveryPropertiesAttributes {
	return snapshotDeliveryPropertiesAttributes{ref: ref}
}

func (sdp snapshotDeliveryPropertiesAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return sdp.ref.InternalTokens()
}

func (sdp snapshotDeliveryPropertiesAttributes) DeliveryFrequency() terra.StringValue {
	return terra.ReferenceAsString(sdp.ref.Append("delivery_frequency"))
}

type SnapshotDeliveryPropertiesState struct {
	DeliveryFrequency string `json:"delivery_frequency"`
}
