// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_iot_provisioning_template

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type PreProvisioningHook struct {
	// PayloadVersion is optional.
	PayloadVersion terra.StringValue `hcl:"payload_version,attr"`
	// TargetArn is required.
	TargetArn terra.StringValue `hcl:"target_arn,attr" validate:"required"`
}

type preProvisioningHookAttributes struct {
	ref terra.Reference
}

func (pph preProvisioningHookAttributes) InternalRef() (terra.Reference, error) {
	return pph.ref, nil
}

func (pph preProvisioningHookAttributes) InternalWithRef(ref terra.Reference) preProvisioningHookAttributes {
	return preProvisioningHookAttributes{ref: ref}
}

func (pph preProvisioningHookAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return pph.ref.InternalTokens()
}

func (pph preProvisioningHookAttributes) PayloadVersion() terra.StringValue {
	return terra.ReferenceAsString(pph.ref.Append("payload_version"))
}

func (pph preProvisioningHookAttributes) TargetArn() terra.StringValue {
	return terra.ReferenceAsString(pph.ref.Append("target_arn"))
}

type PreProvisioningHookState struct {
	PayloadVersion string `json:"payload_version"`
	TargetArn      string `json:"target_arn"`
}
