// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_glue_ml_transform

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type InputRecordTables struct {
	// CatalogId is optional.
	CatalogId terra.StringValue `hcl:"catalog_id,attr"`
	// ConnectionName is optional.
	ConnectionName terra.StringValue `hcl:"connection_name,attr"`
	// DatabaseName is required.
	DatabaseName terra.StringValue `hcl:"database_name,attr" validate:"required"`
	// TableName is required.
	TableName terra.StringValue `hcl:"table_name,attr" validate:"required"`
}

type Parameters struct {
	// TransformType is required.
	TransformType terra.StringValue `hcl:"transform_type,attr" validate:"required"`
	// ParametersFindMatchesParameters is required.
	FindMatchesParameters *ParametersFindMatchesParameters `hcl:"find_matches_parameters,block" validate:"required"`
}

type ParametersFindMatchesParameters struct {
	// AccuracyCostTradeOff is optional.
	AccuracyCostTradeOff terra.NumberValue `hcl:"accuracy_cost_trade_off,attr"`
	// EnforceProvidedLabels is optional.
	EnforceProvidedLabels terra.BoolValue `hcl:"enforce_provided_labels,attr"`
	// PrecisionRecallTradeOff is optional.
	PrecisionRecallTradeOff terra.NumberValue `hcl:"precision_recall_trade_off,attr"`
	// PrimaryKeyColumnName is optional.
	PrimaryKeyColumnName terra.StringValue `hcl:"primary_key_column_name,attr"`
}

type schemaAttributes struct {
	ref terra.Reference
}

func (s schemaAttributes) InternalRef() (terra.Reference, error) {
	return s.ref, nil
}

func (s schemaAttributes) InternalWithRef(ref terra.Reference) schemaAttributes {
	return schemaAttributes{ref: ref}
}

func (s schemaAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return s.ref.InternalTokens()
}

func (s schemaAttributes) DataType() terra.StringValue {
	return terra.ReferenceAsString(s.ref.Append("data_type"))
}

func (s schemaAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(s.ref.Append("name"))
}

type inputRecordTablesAttributes struct {
	ref terra.Reference
}

func (irt inputRecordTablesAttributes) InternalRef() (terra.Reference, error) {
	return irt.ref, nil
}

func (irt inputRecordTablesAttributes) InternalWithRef(ref terra.Reference) inputRecordTablesAttributes {
	return inputRecordTablesAttributes{ref: ref}
}

func (irt inputRecordTablesAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return irt.ref.InternalTokens()
}

func (irt inputRecordTablesAttributes) CatalogId() terra.StringValue {
	return terra.ReferenceAsString(irt.ref.Append("catalog_id"))
}

func (irt inputRecordTablesAttributes) ConnectionName() terra.StringValue {
	return terra.ReferenceAsString(irt.ref.Append("connection_name"))
}

func (irt inputRecordTablesAttributes) DatabaseName() terra.StringValue {
	return terra.ReferenceAsString(irt.ref.Append("database_name"))
}

func (irt inputRecordTablesAttributes) TableName() terra.StringValue {
	return terra.ReferenceAsString(irt.ref.Append("table_name"))
}

type parametersAttributes struct {
	ref terra.Reference
}

func (p parametersAttributes) InternalRef() (terra.Reference, error) {
	return p.ref, nil
}

func (p parametersAttributes) InternalWithRef(ref terra.Reference) parametersAttributes {
	return parametersAttributes{ref: ref}
}

func (p parametersAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return p.ref.InternalTokens()
}

func (p parametersAttributes) TransformType() terra.StringValue {
	return terra.ReferenceAsString(p.ref.Append("transform_type"))
}

func (p parametersAttributes) FindMatchesParameters() terra.ListValue[parametersFindMatchesParametersAttributes] {
	return terra.ReferenceAsList[parametersFindMatchesParametersAttributes](p.ref.Append("find_matches_parameters"))
}

type parametersFindMatchesParametersAttributes struct {
	ref terra.Reference
}

func (fmp parametersFindMatchesParametersAttributes) InternalRef() (terra.Reference, error) {
	return fmp.ref, nil
}

func (fmp parametersFindMatchesParametersAttributes) InternalWithRef(ref terra.Reference) parametersFindMatchesParametersAttributes {
	return parametersFindMatchesParametersAttributes{ref: ref}
}

func (fmp parametersFindMatchesParametersAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return fmp.ref.InternalTokens()
}

func (fmp parametersFindMatchesParametersAttributes) AccuracyCostTradeOff() terra.NumberValue {
	return terra.ReferenceAsNumber(fmp.ref.Append("accuracy_cost_trade_off"))
}

func (fmp parametersFindMatchesParametersAttributes) EnforceProvidedLabels() terra.BoolValue {
	return terra.ReferenceAsBool(fmp.ref.Append("enforce_provided_labels"))
}

func (fmp parametersFindMatchesParametersAttributes) PrecisionRecallTradeOff() terra.NumberValue {
	return terra.ReferenceAsNumber(fmp.ref.Append("precision_recall_trade_off"))
}

func (fmp parametersFindMatchesParametersAttributes) PrimaryKeyColumnName() terra.StringValue {
	return terra.ReferenceAsString(fmp.ref.Append("primary_key_column_name"))
}

type SchemaState struct {
	DataType string `json:"data_type"`
	Name     string `json:"name"`
}

type InputRecordTablesState struct {
	CatalogId      string `json:"catalog_id"`
	ConnectionName string `json:"connection_name"`
	DatabaseName   string `json:"database_name"`
	TableName      string `json:"table_name"`
}

type ParametersState struct {
	TransformType         string                                 `json:"transform_type"`
	FindMatchesParameters []ParametersFindMatchesParametersState `json:"find_matches_parameters"`
}

type ParametersFindMatchesParametersState struct {
	AccuracyCostTradeOff    float64 `json:"accuracy_cost_trade_off"`
	EnforceProvidedLabels   bool    `json:"enforce_provided_labels"`
	PrecisionRecallTradeOff float64 `json:"precision_recall_trade_off"`
	PrimaryKeyColumnName    string  `json:"primary_key_column_name"`
}
