// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_quicksight_iam_policy_assignment

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type Identities struct {
	// Group is optional.
	Group terra.SetValue[terra.StringValue] `hcl:"group,attr"`
	// User is optional.
	User terra.SetValue[terra.StringValue] `hcl:"user,attr"`
}

type identitiesAttributes struct {
	ref terra.Reference
}

func (i identitiesAttributes) InternalRef() (terra.Reference, error) {
	return i.ref, nil
}

func (i identitiesAttributes) InternalWithRef(ref terra.Reference) identitiesAttributes {
	return identitiesAttributes{ref: ref}
}

func (i identitiesAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return i.ref.InternalTokens()
}

func (i identitiesAttributes) Group() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](i.ref.Append("group"))
}

func (i identitiesAttributes) User() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](i.ref.Append("user"))
}

type IdentitiesState struct {
	Group []string `json:"group"`
	User  []string `json:"user"`
}
