// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_sagemaker_space

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type SpaceSettings struct {
	// SpaceSettingsJupyterServerAppSettings is optional.
	JupyterServerAppSettings *SpaceSettingsJupyterServerAppSettings `hcl:"jupyter_server_app_settings,block"`
	// SpaceSettingsKernelGatewayAppSettings is optional.
	KernelGatewayAppSettings *SpaceSettingsKernelGatewayAppSettings `hcl:"kernel_gateway_app_settings,block"`
}

type SpaceSettingsJupyterServerAppSettings struct {
	// LifecycleConfigArns is optional.
	LifecycleConfigArns terra.SetValue[terra.StringValue] `hcl:"lifecycle_config_arns,attr"`
	// SpaceSettingsJupyterServerAppSettingsCodeRepository is min=0,max=10.
	CodeRepository []SpaceSettingsJupyterServerAppSettingsCodeRepository `hcl:"code_repository,block" validate:"min=0,max=10"`
	// SpaceSettingsJupyterServerAppSettingsDefaultResourceSpec is required.
	DefaultResourceSpec *SpaceSettingsJupyterServerAppSettingsDefaultResourceSpec `hcl:"default_resource_spec,block" validate:"required"`
}

type SpaceSettingsJupyterServerAppSettingsCodeRepository struct {
	// RepositoryUrl is required.
	RepositoryUrl terra.StringValue `hcl:"repository_url,attr" validate:"required"`
}

type SpaceSettingsJupyterServerAppSettingsDefaultResourceSpec struct {
	// InstanceType is optional.
	InstanceType terra.StringValue `hcl:"instance_type,attr"`
	// LifecycleConfigArn is optional.
	LifecycleConfigArn terra.StringValue `hcl:"lifecycle_config_arn,attr"`
	// SagemakerImageArn is optional.
	SagemakerImageArn terra.StringValue `hcl:"sagemaker_image_arn,attr"`
	// SagemakerImageVersionArn is optional.
	SagemakerImageVersionArn terra.StringValue `hcl:"sagemaker_image_version_arn,attr"`
}

type SpaceSettingsKernelGatewayAppSettings struct {
	// LifecycleConfigArns is optional.
	LifecycleConfigArns terra.SetValue[terra.StringValue] `hcl:"lifecycle_config_arns,attr"`
	// SpaceSettingsKernelGatewayAppSettingsCustomImage is min=0,max=30.
	CustomImage []SpaceSettingsKernelGatewayAppSettingsCustomImage `hcl:"custom_image,block" validate:"min=0,max=30"`
	// SpaceSettingsKernelGatewayAppSettingsDefaultResourceSpec is required.
	DefaultResourceSpec *SpaceSettingsKernelGatewayAppSettingsDefaultResourceSpec `hcl:"default_resource_spec,block" validate:"required"`
}

type SpaceSettingsKernelGatewayAppSettingsCustomImage struct {
	// AppImageConfigName is required.
	AppImageConfigName terra.StringValue `hcl:"app_image_config_name,attr" validate:"required"`
	// ImageName is required.
	ImageName terra.StringValue `hcl:"image_name,attr" validate:"required"`
	// ImageVersionNumber is optional.
	ImageVersionNumber terra.NumberValue `hcl:"image_version_number,attr"`
}

type SpaceSettingsKernelGatewayAppSettingsDefaultResourceSpec struct {
	// InstanceType is optional.
	InstanceType terra.StringValue `hcl:"instance_type,attr"`
	// LifecycleConfigArn is optional.
	LifecycleConfigArn terra.StringValue `hcl:"lifecycle_config_arn,attr"`
	// SagemakerImageArn is optional.
	SagemakerImageArn terra.StringValue `hcl:"sagemaker_image_arn,attr"`
	// SagemakerImageVersionArn is optional.
	SagemakerImageVersionArn terra.StringValue `hcl:"sagemaker_image_version_arn,attr"`
}

type spaceSettingsAttributes struct {
	ref terra.Reference
}

func (ss spaceSettingsAttributes) InternalRef() (terra.Reference, error) {
	return ss.ref, nil
}

func (ss spaceSettingsAttributes) InternalWithRef(ref terra.Reference) spaceSettingsAttributes {
	return spaceSettingsAttributes{ref: ref}
}

func (ss spaceSettingsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ss.ref.InternalTokens()
}

func (ss spaceSettingsAttributes) JupyterServerAppSettings() terra.ListValue[spaceSettingsJupyterServerAppSettingsAttributes] {
	return terra.ReferenceAsList[spaceSettingsJupyterServerAppSettingsAttributes](ss.ref.Append("jupyter_server_app_settings"))
}

func (ss spaceSettingsAttributes) KernelGatewayAppSettings() terra.ListValue[spaceSettingsKernelGatewayAppSettingsAttributes] {
	return terra.ReferenceAsList[spaceSettingsKernelGatewayAppSettingsAttributes](ss.ref.Append("kernel_gateway_app_settings"))
}

type spaceSettingsJupyterServerAppSettingsAttributes struct {
	ref terra.Reference
}

func (jsas spaceSettingsJupyterServerAppSettingsAttributes) InternalRef() (terra.Reference, error) {
	return jsas.ref, nil
}

func (jsas spaceSettingsJupyterServerAppSettingsAttributes) InternalWithRef(ref terra.Reference) spaceSettingsJupyterServerAppSettingsAttributes {
	return spaceSettingsJupyterServerAppSettingsAttributes{ref: ref}
}

func (jsas spaceSettingsJupyterServerAppSettingsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return jsas.ref.InternalTokens()
}

func (jsas spaceSettingsJupyterServerAppSettingsAttributes) LifecycleConfigArns() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](jsas.ref.Append("lifecycle_config_arns"))
}

func (jsas spaceSettingsJupyterServerAppSettingsAttributes) CodeRepository() terra.SetValue[spaceSettingsJupyterServerAppSettingsCodeRepositoryAttributes] {
	return terra.ReferenceAsSet[spaceSettingsJupyterServerAppSettingsCodeRepositoryAttributes](jsas.ref.Append("code_repository"))
}

func (jsas spaceSettingsJupyterServerAppSettingsAttributes) DefaultResourceSpec() terra.ListValue[spaceSettingsJupyterServerAppSettingsDefaultResourceSpecAttributes] {
	return terra.ReferenceAsList[spaceSettingsJupyterServerAppSettingsDefaultResourceSpecAttributes](jsas.ref.Append("default_resource_spec"))
}

type spaceSettingsJupyterServerAppSettingsCodeRepositoryAttributes struct {
	ref terra.Reference
}

func (cr spaceSettingsJupyterServerAppSettingsCodeRepositoryAttributes) InternalRef() (terra.Reference, error) {
	return cr.ref, nil
}

func (cr spaceSettingsJupyterServerAppSettingsCodeRepositoryAttributes) InternalWithRef(ref terra.Reference) spaceSettingsJupyterServerAppSettingsCodeRepositoryAttributes {
	return spaceSettingsJupyterServerAppSettingsCodeRepositoryAttributes{ref: ref}
}

func (cr spaceSettingsJupyterServerAppSettingsCodeRepositoryAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return cr.ref.InternalTokens()
}

func (cr spaceSettingsJupyterServerAppSettingsCodeRepositoryAttributes) RepositoryUrl() terra.StringValue {
	return terra.ReferenceAsString(cr.ref.Append("repository_url"))
}

type spaceSettingsJupyterServerAppSettingsDefaultResourceSpecAttributes struct {
	ref terra.Reference
}

func (drs spaceSettingsJupyterServerAppSettingsDefaultResourceSpecAttributes) InternalRef() (terra.Reference, error) {
	return drs.ref, nil
}

func (drs spaceSettingsJupyterServerAppSettingsDefaultResourceSpecAttributes) InternalWithRef(ref terra.Reference) spaceSettingsJupyterServerAppSettingsDefaultResourceSpecAttributes {
	return spaceSettingsJupyterServerAppSettingsDefaultResourceSpecAttributes{ref: ref}
}

func (drs spaceSettingsJupyterServerAppSettingsDefaultResourceSpecAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return drs.ref.InternalTokens()
}

func (drs spaceSettingsJupyterServerAppSettingsDefaultResourceSpecAttributes) InstanceType() terra.StringValue {
	return terra.ReferenceAsString(drs.ref.Append("instance_type"))
}

func (drs spaceSettingsJupyterServerAppSettingsDefaultResourceSpecAttributes) LifecycleConfigArn() terra.StringValue {
	return terra.ReferenceAsString(drs.ref.Append("lifecycle_config_arn"))
}

func (drs spaceSettingsJupyterServerAppSettingsDefaultResourceSpecAttributes) SagemakerImageArn() terra.StringValue {
	return terra.ReferenceAsString(drs.ref.Append("sagemaker_image_arn"))
}

func (drs spaceSettingsJupyterServerAppSettingsDefaultResourceSpecAttributes) SagemakerImageVersionArn() terra.StringValue {
	return terra.ReferenceAsString(drs.ref.Append("sagemaker_image_version_arn"))
}

type spaceSettingsKernelGatewayAppSettingsAttributes struct {
	ref terra.Reference
}

func (kgas spaceSettingsKernelGatewayAppSettingsAttributes) InternalRef() (terra.Reference, error) {
	return kgas.ref, nil
}

func (kgas spaceSettingsKernelGatewayAppSettingsAttributes) InternalWithRef(ref terra.Reference) spaceSettingsKernelGatewayAppSettingsAttributes {
	return spaceSettingsKernelGatewayAppSettingsAttributes{ref: ref}
}

func (kgas spaceSettingsKernelGatewayAppSettingsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return kgas.ref.InternalTokens()
}

func (kgas spaceSettingsKernelGatewayAppSettingsAttributes) LifecycleConfigArns() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](kgas.ref.Append("lifecycle_config_arns"))
}

func (kgas spaceSettingsKernelGatewayAppSettingsAttributes) CustomImage() terra.ListValue[spaceSettingsKernelGatewayAppSettingsCustomImageAttributes] {
	return terra.ReferenceAsList[spaceSettingsKernelGatewayAppSettingsCustomImageAttributes](kgas.ref.Append("custom_image"))
}

func (kgas spaceSettingsKernelGatewayAppSettingsAttributes) DefaultResourceSpec() terra.ListValue[spaceSettingsKernelGatewayAppSettingsDefaultResourceSpecAttributes] {
	return terra.ReferenceAsList[spaceSettingsKernelGatewayAppSettingsDefaultResourceSpecAttributes](kgas.ref.Append("default_resource_spec"))
}

type spaceSettingsKernelGatewayAppSettingsCustomImageAttributes struct {
	ref terra.Reference
}

func (ci spaceSettingsKernelGatewayAppSettingsCustomImageAttributes) InternalRef() (terra.Reference, error) {
	return ci.ref, nil
}

func (ci spaceSettingsKernelGatewayAppSettingsCustomImageAttributes) InternalWithRef(ref terra.Reference) spaceSettingsKernelGatewayAppSettingsCustomImageAttributes {
	return spaceSettingsKernelGatewayAppSettingsCustomImageAttributes{ref: ref}
}

func (ci spaceSettingsKernelGatewayAppSettingsCustomImageAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ci.ref.InternalTokens()
}

func (ci spaceSettingsKernelGatewayAppSettingsCustomImageAttributes) AppImageConfigName() terra.StringValue {
	return terra.ReferenceAsString(ci.ref.Append("app_image_config_name"))
}

func (ci spaceSettingsKernelGatewayAppSettingsCustomImageAttributes) ImageName() terra.StringValue {
	return terra.ReferenceAsString(ci.ref.Append("image_name"))
}

func (ci spaceSettingsKernelGatewayAppSettingsCustomImageAttributes) ImageVersionNumber() terra.NumberValue {
	return terra.ReferenceAsNumber(ci.ref.Append("image_version_number"))
}

type spaceSettingsKernelGatewayAppSettingsDefaultResourceSpecAttributes struct {
	ref terra.Reference
}

func (drs spaceSettingsKernelGatewayAppSettingsDefaultResourceSpecAttributes) InternalRef() (terra.Reference, error) {
	return drs.ref, nil
}

func (drs spaceSettingsKernelGatewayAppSettingsDefaultResourceSpecAttributes) InternalWithRef(ref terra.Reference) spaceSettingsKernelGatewayAppSettingsDefaultResourceSpecAttributes {
	return spaceSettingsKernelGatewayAppSettingsDefaultResourceSpecAttributes{ref: ref}
}

func (drs spaceSettingsKernelGatewayAppSettingsDefaultResourceSpecAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return drs.ref.InternalTokens()
}

func (drs spaceSettingsKernelGatewayAppSettingsDefaultResourceSpecAttributes) InstanceType() terra.StringValue {
	return terra.ReferenceAsString(drs.ref.Append("instance_type"))
}

func (drs spaceSettingsKernelGatewayAppSettingsDefaultResourceSpecAttributes) LifecycleConfigArn() terra.StringValue {
	return terra.ReferenceAsString(drs.ref.Append("lifecycle_config_arn"))
}

func (drs spaceSettingsKernelGatewayAppSettingsDefaultResourceSpecAttributes) SagemakerImageArn() terra.StringValue {
	return terra.ReferenceAsString(drs.ref.Append("sagemaker_image_arn"))
}

func (drs spaceSettingsKernelGatewayAppSettingsDefaultResourceSpecAttributes) SagemakerImageVersionArn() terra.StringValue {
	return terra.ReferenceAsString(drs.ref.Append("sagemaker_image_version_arn"))
}

type SpaceSettingsState struct {
	JupyterServerAppSettings []SpaceSettingsJupyterServerAppSettingsState `json:"jupyter_server_app_settings"`
	KernelGatewayAppSettings []SpaceSettingsKernelGatewayAppSettingsState `json:"kernel_gateway_app_settings"`
}

type SpaceSettingsJupyterServerAppSettingsState struct {
	LifecycleConfigArns []string                                                        `json:"lifecycle_config_arns"`
	CodeRepository      []SpaceSettingsJupyterServerAppSettingsCodeRepositoryState      `json:"code_repository"`
	DefaultResourceSpec []SpaceSettingsJupyterServerAppSettingsDefaultResourceSpecState `json:"default_resource_spec"`
}

type SpaceSettingsJupyterServerAppSettingsCodeRepositoryState struct {
	RepositoryUrl string `json:"repository_url"`
}

type SpaceSettingsJupyterServerAppSettingsDefaultResourceSpecState struct {
	InstanceType             string `json:"instance_type"`
	LifecycleConfigArn       string `json:"lifecycle_config_arn"`
	SagemakerImageArn        string `json:"sagemaker_image_arn"`
	SagemakerImageVersionArn string `json:"sagemaker_image_version_arn"`
}

type SpaceSettingsKernelGatewayAppSettingsState struct {
	LifecycleConfigArns []string                                                        `json:"lifecycle_config_arns"`
	CustomImage         []SpaceSettingsKernelGatewayAppSettingsCustomImageState         `json:"custom_image"`
	DefaultResourceSpec []SpaceSettingsKernelGatewayAppSettingsDefaultResourceSpecState `json:"default_resource_spec"`
}

type SpaceSettingsKernelGatewayAppSettingsCustomImageState struct {
	AppImageConfigName string  `json:"app_image_config_name"`
	ImageName          string  `json:"image_name"`
	ImageVersionNumber float64 `json:"image_version_number"`
}

type SpaceSettingsKernelGatewayAppSettingsDefaultResourceSpecState struct {
	InstanceType             string `json:"instance_type"`
	LifecycleConfigArn       string `json:"lifecycle_config_arn"`
	SagemakerImageArn        string `json:"sagemaker_image_arn"`
	SagemakerImageVersionArn string `json:"sagemaker_image_version_arn"`
}
