// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_codecommit_trigger

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type Trigger struct {
	// Branches is optional.
	Branches terra.ListValue[terra.StringValue] `hcl:"branches,attr"`
	// CustomData is optional.
	CustomData terra.StringValue `hcl:"custom_data,attr"`
	// DestinationArn is required.
	DestinationArn terra.StringValue `hcl:"destination_arn,attr" validate:"required"`
	// Events is required.
	Events terra.ListValue[terra.StringValue] `hcl:"events,attr" validate:"required"`
	// Name is required.
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
}

type triggerAttributes struct {
	ref terra.Reference
}

func (t triggerAttributes) InternalRef() (terra.Reference, error) {
	return t.ref, nil
}

func (t triggerAttributes) InternalWithRef(ref terra.Reference) triggerAttributes {
	return triggerAttributes{ref: ref}
}

func (t triggerAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return t.ref.InternalTokens()
}

func (t triggerAttributes) Branches() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](t.ref.Append("branches"))
}

func (t triggerAttributes) CustomData() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("custom_data"))
}

func (t triggerAttributes) DestinationArn() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("destination_arn"))
}

func (t triggerAttributes) Events() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](t.ref.Append("events"))
}

func (t triggerAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("name"))
}

type TriggerState struct {
	Branches       []string `json:"branches"`
	CustomData     string   `json:"custom_data"`
	DestinationArn string   `json:"destination_arn"`
	Events         []string `json:"events"`
	Name           string   `json:"name"`
}
