// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_ecr_image

import "github.com/golingon/lingon/pkg/terra"

var _ terra.DataSource = (*DataSource)(nil)

/*
DataSource is the data source aws_ecr_image.

Documentation: https://registry.terraform.io/providers/hashicorp/aws/5.0.0/docs
*/
type DataSource struct {
	Name string
	Args DataArgs
}

// DataSource returns the Terraform object type for [DataSource].
func (aei *DataSource) DataSource() string {
	return "aws_ecr_image"
}

// LocalName returns the local name for [DataSource].
func (aei *DataSource) LocalName() string {
	return aei.Name
}

// Configuration returns the configuration (args) for [DataSource].
func (aei *DataSource) Configuration() interface{} {
	return aei.Args
}

// Attributes returns the attributes for [DataSource].
func (aei *DataSource) Attributes() dataAwsEcrImageAttributes {
	return dataAwsEcrImageAttributes{ref: terra.ReferenceDataSource(aei)}
}

// DataArgs contains the configurations for aws_ecr_image.
type DataArgs struct {
	// Id is optional.
	Id terra.StringValue `hcl:"id,attr"`
	// ImageDigest is optional.
	ImageDigest terra.StringValue `hcl:"image_digest,attr"`
	// ImageTag is optional.
	ImageTag terra.StringValue `hcl:"image_tag,attr"`
	// MostRecent is optional.
	MostRecent terra.BoolValue `hcl:"most_recent,attr"`
	// RegistryId is optional.
	RegistryId terra.StringValue `hcl:"registry_id,attr"`
	// RepositoryName is required.
	RepositoryName terra.StringValue `hcl:"repository_name,attr" validate:"required"`
}

type dataAwsEcrImageAttributes struct {
	ref terra.Reference
}

// Id returns a reference to field id of aws_ecr_image.
func (aei dataAwsEcrImageAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(aei.ref.Append("id"))
}

// ImageDigest returns a reference to field image_digest of aws_ecr_image.
func (aei dataAwsEcrImageAttributes) ImageDigest() terra.StringValue {
	return terra.ReferenceAsString(aei.ref.Append("image_digest"))
}

// ImagePushedAt returns a reference to field image_pushed_at of aws_ecr_image.
func (aei dataAwsEcrImageAttributes) ImagePushedAt() terra.NumberValue {
	return terra.ReferenceAsNumber(aei.ref.Append("image_pushed_at"))
}

// ImageSizeInBytes returns a reference to field image_size_in_bytes of aws_ecr_image.
func (aei dataAwsEcrImageAttributes) ImageSizeInBytes() terra.NumberValue {
	return terra.ReferenceAsNumber(aei.ref.Append("image_size_in_bytes"))
}

// ImageTag returns a reference to field image_tag of aws_ecr_image.
func (aei dataAwsEcrImageAttributes) ImageTag() terra.StringValue {
	return terra.ReferenceAsString(aei.ref.Append("image_tag"))
}

// ImageTags returns a reference to field image_tags of aws_ecr_image.
func (aei dataAwsEcrImageAttributes) ImageTags() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](aei.ref.Append("image_tags"))
}

// MostRecent returns a reference to field most_recent of aws_ecr_image.
func (aei dataAwsEcrImageAttributes) MostRecent() terra.BoolValue {
	return terra.ReferenceAsBool(aei.ref.Append("most_recent"))
}

// RegistryId returns a reference to field registry_id of aws_ecr_image.
func (aei dataAwsEcrImageAttributes) RegistryId() terra.StringValue {
	return terra.ReferenceAsString(aei.ref.Append("registry_id"))
}

// RepositoryName returns a reference to field repository_name of aws_ecr_image.
func (aei dataAwsEcrImageAttributes) RepositoryName() terra.StringValue {
	return terra.ReferenceAsString(aei.ref.Append("repository_name"))
}
