// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_ssm_document

import "github.com/golingon/lingon/pkg/terra"

var _ terra.DataSource = (*DataSource)(nil)

/*
DataSource is the data source aws_ssm_document.

Documentation: https://registry.terraform.io/providers/hashicorp/aws/5.0.0/docs
*/
type DataSource struct {
	Name string
	Args DataArgs
}

// DataSource returns the Terraform object type for [DataSource].
func (asd *DataSource) DataSource() string {
	return "aws_ssm_document"
}

// LocalName returns the local name for [DataSource].
func (asd *DataSource) LocalName() string {
	return asd.Name
}

// Configuration returns the configuration (args) for [DataSource].
func (asd *DataSource) Configuration() interface{} {
	return asd.Args
}

// Attributes returns the attributes for [DataSource].
func (asd *DataSource) Attributes() dataAwsSsmDocumentAttributes {
	return dataAwsSsmDocumentAttributes{ref: terra.ReferenceDataSource(asd)}
}

// DataArgs contains the configurations for aws_ssm_document.
type DataArgs struct {
	// DocumentFormat is optional.
	DocumentFormat terra.StringValue `hcl:"document_format,attr"`
	// DocumentVersion is optional.
	DocumentVersion terra.StringValue `hcl:"document_version,attr"`
	// Id is optional.
	Id terra.StringValue `hcl:"id,attr"`
	// Name is required.
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
}

type dataAwsSsmDocumentAttributes struct {
	ref terra.Reference
}

// Arn returns a reference to field arn of aws_ssm_document.
func (asd dataAwsSsmDocumentAttributes) Arn() terra.StringValue {
	return terra.ReferenceAsString(asd.ref.Append("arn"))
}

// Content returns a reference to field content of aws_ssm_document.
func (asd dataAwsSsmDocumentAttributes) Content() terra.StringValue {
	return terra.ReferenceAsString(asd.ref.Append("content"))
}

// DocumentFormat returns a reference to field document_format of aws_ssm_document.
func (asd dataAwsSsmDocumentAttributes) DocumentFormat() terra.StringValue {
	return terra.ReferenceAsString(asd.ref.Append("document_format"))
}

// DocumentType returns a reference to field document_type of aws_ssm_document.
func (asd dataAwsSsmDocumentAttributes) DocumentType() terra.StringValue {
	return terra.ReferenceAsString(asd.ref.Append("document_type"))
}

// DocumentVersion returns a reference to field document_version of aws_ssm_document.
func (asd dataAwsSsmDocumentAttributes) DocumentVersion() terra.StringValue {
	return terra.ReferenceAsString(asd.ref.Append("document_version"))
}

// Id returns a reference to field id of aws_ssm_document.
func (asd dataAwsSsmDocumentAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(asd.ref.Append("id"))
}

// Name returns a reference to field name of aws_ssm_document.
func (asd dataAwsSsmDocumentAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(asd.ref.Append("name"))
}
