// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_sagemaker_device_fleet

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type OutputConfig struct {
	// KmsKeyId is optional.
	KmsKeyId terra.StringValue `hcl:"kms_key_id,attr"`
	// S3OutputLocation is required.
	S3OutputLocation terra.StringValue `hcl:"s3_output_location,attr" validate:"required"`
}

type outputConfigAttributes struct {
	ref terra.Reference
}

func (oc outputConfigAttributes) InternalRef() (terra.Reference, error) {
	return oc.ref, nil
}

func (oc outputConfigAttributes) InternalWithRef(ref terra.Reference) outputConfigAttributes {
	return outputConfigAttributes{ref: ref}
}

func (oc outputConfigAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return oc.ref.InternalTokens()
}

func (oc outputConfigAttributes) KmsKeyId() terra.StringValue {
	return terra.ReferenceAsString(oc.ref.Append("kms_key_id"))
}

func (oc outputConfigAttributes) S3OutputLocation() terra.StringValue {
	return terra.ReferenceAsString(oc.ref.Append("s3_output_location"))
}

type OutputConfigState struct {
	KmsKeyId         string `json:"kms_key_id"`
	S3OutputLocation string `json:"s3_output_location"`
}
