// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_sesv2_dedicated_ip_pool

import "github.com/golingon/lingon/pkg/terra"

var _ terra.DataSource = (*DataSource)(nil)

/*
DataSource is the data source aws_sesv2_dedicated_ip_pool.

Documentation: https://registry.terraform.io/providers/hashicorp/aws/5.0.0/docs
*/
type DataSource struct {
	Name string
	Args DataArgs
}

// DataSource returns the Terraform object type for [DataSource].
func (asdip *DataSource) DataSource() string {
	return "aws_sesv2_dedicated_ip_pool"
}

// LocalName returns the local name for [DataSource].
func (asdip *DataSource) LocalName() string {
	return asdip.Name
}

// Configuration returns the configuration (args) for [DataSource].
func (asdip *DataSource) Configuration() interface{} {
	return asdip.Args
}

// Attributes returns the attributes for [DataSource].
func (asdip *DataSource) Attributes() dataAwsSesv2DedicatedIpPoolAttributes {
	return dataAwsSesv2DedicatedIpPoolAttributes{ref: terra.ReferenceDataSource(asdip)}
}

// DataArgs contains the configurations for aws_sesv2_dedicated_ip_pool.
type DataArgs struct {
	// Id is optional.
	Id terra.StringValue `hcl:"id,attr"`
	// PoolName is required.
	PoolName terra.StringValue `hcl:"pool_name,attr" validate:"required"`
	// Tags is optional.
	Tags terra.MapValue[terra.StringValue] `hcl:"tags,attr"`
}

type dataAwsSesv2DedicatedIpPoolAttributes struct {
	ref terra.Reference
}

// Arn returns a reference to field arn of aws_sesv2_dedicated_ip_pool.
func (asdip dataAwsSesv2DedicatedIpPoolAttributes) Arn() terra.StringValue {
	return terra.ReferenceAsString(asdip.ref.Append("arn"))
}

// Id returns a reference to field id of aws_sesv2_dedicated_ip_pool.
func (asdip dataAwsSesv2DedicatedIpPoolAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(asdip.ref.Append("id"))
}

// PoolName returns a reference to field pool_name of aws_sesv2_dedicated_ip_pool.
func (asdip dataAwsSesv2DedicatedIpPoolAttributes) PoolName() terra.StringValue {
	return terra.ReferenceAsString(asdip.ref.Append("pool_name"))
}

// ScalingMode returns a reference to field scaling_mode of aws_sesv2_dedicated_ip_pool.
func (asdip dataAwsSesv2DedicatedIpPoolAttributes) ScalingMode() terra.StringValue {
	return terra.ReferenceAsString(asdip.ref.Append("scaling_mode"))
}

// Tags returns a reference to field tags of aws_sesv2_dedicated_ip_pool.
func (asdip dataAwsSesv2DedicatedIpPoolAttributes) Tags() terra.MapValue[terra.StringValue] {
	return terra.ReferenceAsMap[terra.StringValue](asdip.ref.Append("tags"))
}

func (asdip dataAwsSesv2DedicatedIpPoolAttributes) DedicatedIps() terra.ListValue[DatadedicatedIpsAttributes] {
	return terra.ReferenceAsList[DatadedicatedIpsAttributes](asdip.ref.Append("dedicated_ips"))
}
