// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_autoscaling_policy

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type PredictiveScalingConfiguration struct {
	// MaxCapacityBreachBehavior is optional.
	MaxCapacityBreachBehavior terra.StringValue `hcl:"max_capacity_breach_behavior,attr"`
	// MaxCapacityBuffer is optional.
	MaxCapacityBuffer terra.StringValue `hcl:"max_capacity_buffer,attr"`
	// Mode is optional.
	Mode terra.StringValue `hcl:"mode,attr"`
	// SchedulingBufferTime is optional.
	SchedulingBufferTime terra.StringValue `hcl:"scheduling_buffer_time,attr"`
	// PredictiveScalingConfigurationMetricSpecification is required.
	MetricSpecification *PredictiveScalingConfigurationMetricSpecification `hcl:"metric_specification,block" validate:"required"`
}

type PredictiveScalingConfigurationMetricSpecification struct {
	// TargetValue is required.
	TargetValue terra.NumberValue `hcl:"target_value,attr" validate:"required"`
	// PredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecification is optional.
	CustomizedCapacityMetricSpecification *PredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecification `hcl:"customized_capacity_metric_specification,block"`
	// PredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecification is optional.
	CustomizedLoadMetricSpecification *PredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecification `hcl:"customized_load_metric_specification,block"`
	// PredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecification is optional.
	CustomizedScalingMetricSpecification *PredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecification `hcl:"customized_scaling_metric_specification,block"`
	// PredictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecification is optional.
	PredefinedLoadMetricSpecification *PredictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecification `hcl:"predefined_load_metric_specification,block"`
	// PredictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecification is optional.
	PredefinedMetricPairSpecification *PredictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecification `hcl:"predefined_metric_pair_specification,block"`
	// PredictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecification is optional.
	PredefinedScalingMetricSpecification *PredictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecification `hcl:"predefined_scaling_metric_specification,block"`
}

type PredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecification struct {
	// PredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueries is min=1,max=10.
	MetricDataQueries []PredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueries `hcl:"metric_data_queries,block" validate:"min=1,max=10"`
}

type PredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueries struct {
	// Expression is optional.
	Expression terra.StringValue `hcl:"expression,attr"`
	// Id is required.
	Id terra.StringValue `hcl:"id,attr" validate:"required"`
	// Label is optional.
	Label terra.StringValue `hcl:"label,attr"`
	// ReturnData is optional.
	ReturnData terra.BoolValue `hcl:"return_data,attr"`
	// PredictiveScalingConfigurationMetricSpecification716314D0 is optional.
	MetricStat *PredictiveScalingConfigurationMetricSpecification716314D0 `hcl:"metric_stat,block"`
}

type PredictiveScalingConfigurationMetricSpecification716314D0 struct {
	// Stat is required.
	Stat terra.StringValue `hcl:"stat,attr" validate:"required"`
	// Unit is optional.
	Unit terra.StringValue `hcl:"unit,attr"`
	// PredictiveScalingConfigurationMetricSpecification63A47Dc5 is required.
	Metric *PredictiveScalingConfigurationMetricSpecification63A47Dc5 `hcl:"metric,block" validate:"required"`
}

type PredictiveScalingConfigurationMetricSpecification63A47Dc5 struct {
	// MetricName is required.
	MetricName terra.StringValue `hcl:"metric_name,attr" validate:"required"`
	// Namespace is required.
	Namespace terra.StringValue `hcl:"namespace,attr" validate:"required"`
	// PredictiveScalingConfigurationMetricSpecification8Ef8Ae96 is min=0.
	Dimensions []PredictiveScalingConfigurationMetricSpecification8Ef8Ae96 `hcl:"dimensions,block" validate:"min=0"`
}

type PredictiveScalingConfigurationMetricSpecification8Ef8Ae96 struct {
	// Name is required.
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// Value is required.
	Value terra.StringValue `hcl:"value,attr" validate:"required"`
}

type PredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecification struct {
	// PredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueries is min=1,max=10.
	MetricDataQueries []PredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueries `hcl:"metric_data_queries,block" validate:"min=1,max=10"`
}

type PredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueries struct {
	// Expression is optional.
	Expression terra.StringValue `hcl:"expression,attr"`
	// Id is required.
	Id terra.StringValue `hcl:"id,attr" validate:"required"`
	// Label is optional.
	Label terra.StringValue `hcl:"label,attr"`
	// ReturnData is optional.
	ReturnData terra.BoolValue `hcl:"return_data,attr"`
	// PredictiveScalingConfigurationMetricSpecificationB67D72Fe is optional.
	MetricStat *PredictiveScalingConfigurationMetricSpecificationB67D72Fe `hcl:"metric_stat,block"`
}

type PredictiveScalingConfigurationMetricSpecificationB67D72Fe struct {
	// Stat is required.
	Stat terra.StringValue `hcl:"stat,attr" validate:"required"`
	// Unit is optional.
	Unit terra.StringValue `hcl:"unit,attr"`
	// PredictiveScalingConfigurationMetricSpecification5Ec745A9 is required.
	Metric *PredictiveScalingConfigurationMetricSpecification5Ec745A9 `hcl:"metric,block" validate:"required"`
}

type PredictiveScalingConfigurationMetricSpecification5Ec745A9 struct {
	// MetricName is required.
	MetricName terra.StringValue `hcl:"metric_name,attr" validate:"required"`
	// Namespace is required.
	Namespace terra.StringValue `hcl:"namespace,attr" validate:"required"`
	// PredictiveScalingConfigurationMetricSpecificationA484Bbb1 is min=0.
	Dimensions []PredictiveScalingConfigurationMetricSpecificationA484Bbb1 `hcl:"dimensions,block" validate:"min=0"`
}

type PredictiveScalingConfigurationMetricSpecificationA484Bbb1 struct {
	// Name is required.
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// Value is required.
	Value terra.StringValue `hcl:"value,attr" validate:"required"`
}

type PredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecification struct {
	// PredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueries is min=1,max=10.
	MetricDataQueries []PredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueries `hcl:"metric_data_queries,block" validate:"min=1,max=10"`
}

type PredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueries struct {
	// Expression is optional.
	Expression terra.StringValue `hcl:"expression,attr"`
	// Id is required.
	Id terra.StringValue `hcl:"id,attr" validate:"required"`
	// Label is optional.
	Label terra.StringValue `hcl:"label,attr"`
	// ReturnData is optional.
	ReturnData terra.BoolValue `hcl:"return_data,attr"`
	// PredictiveScalingConfigurationMetricSpecification61E4D6D6 is optional.
	MetricStat *PredictiveScalingConfigurationMetricSpecification61E4D6D6 `hcl:"metric_stat,block"`
}

type PredictiveScalingConfigurationMetricSpecification61E4D6D6 struct {
	// Stat is required.
	Stat terra.StringValue `hcl:"stat,attr" validate:"required"`
	// Unit is optional.
	Unit terra.StringValue `hcl:"unit,attr"`
	// PredictiveScalingConfigurationMetricSpecification7A152D67 is required.
	Metric *PredictiveScalingConfigurationMetricSpecification7A152D67 `hcl:"metric,block" validate:"required"`
}

type PredictiveScalingConfigurationMetricSpecification7A152D67 struct {
	// MetricName is required.
	MetricName terra.StringValue `hcl:"metric_name,attr" validate:"required"`
	// Namespace is required.
	Namespace terra.StringValue `hcl:"namespace,attr" validate:"required"`
	// PredictiveScalingConfigurationMetricSpecification56Ac0Cae is min=0.
	Dimensions []PredictiveScalingConfigurationMetricSpecification56Ac0Cae `hcl:"dimensions,block" validate:"min=0"`
}

type PredictiveScalingConfigurationMetricSpecification56Ac0Cae struct {
	// Name is required.
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// Value is required.
	Value terra.StringValue `hcl:"value,attr" validate:"required"`
}

type PredictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecification struct {
	// PredefinedMetricType is required.
	PredefinedMetricType terra.StringValue `hcl:"predefined_metric_type,attr" validate:"required"`
	// ResourceLabel is optional.
	ResourceLabel terra.StringValue `hcl:"resource_label,attr"`
}

type PredictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecification struct {
	// PredefinedMetricType is required.
	PredefinedMetricType terra.StringValue `hcl:"predefined_metric_type,attr" validate:"required"`
	// ResourceLabel is optional.
	ResourceLabel terra.StringValue `hcl:"resource_label,attr"`
}

type PredictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecification struct {
	// PredefinedMetricType is required.
	PredefinedMetricType terra.StringValue `hcl:"predefined_metric_type,attr" validate:"required"`
	// ResourceLabel is optional.
	ResourceLabel terra.StringValue `hcl:"resource_label,attr"`
}

type StepAdjustment struct {
	// MetricIntervalLowerBound is optional.
	MetricIntervalLowerBound terra.StringValue `hcl:"metric_interval_lower_bound,attr"`
	// MetricIntervalUpperBound is optional.
	MetricIntervalUpperBound terra.StringValue `hcl:"metric_interval_upper_bound,attr"`
	// ScalingAdjustment is required.
	ScalingAdjustment terra.NumberValue `hcl:"scaling_adjustment,attr" validate:"required"`
}

type TargetTrackingConfiguration struct {
	// DisableScaleIn is optional.
	DisableScaleIn terra.BoolValue `hcl:"disable_scale_in,attr"`
	// TargetValue is required.
	TargetValue terra.NumberValue `hcl:"target_value,attr" validate:"required"`
	// TargetTrackingConfigurationCustomizedMetricSpecification is optional.
	CustomizedMetricSpecification *TargetTrackingConfigurationCustomizedMetricSpecification `hcl:"customized_metric_specification,block"`
	// TargetTrackingConfigurationPredefinedMetricSpecification is optional.
	PredefinedMetricSpecification *TargetTrackingConfigurationPredefinedMetricSpecification `hcl:"predefined_metric_specification,block"`
}

type TargetTrackingConfigurationCustomizedMetricSpecification struct {
	// MetricName is optional.
	MetricName terra.StringValue `hcl:"metric_name,attr"`
	// Namespace is optional.
	Namespace terra.StringValue `hcl:"namespace,attr"`
	// Statistic is optional.
	Statistic terra.StringValue `hcl:"statistic,attr"`
	// Unit is optional.
	Unit terra.StringValue `hcl:"unit,attr"`
	// TargetTrackingConfigurationCustomizedMetricSpecificationMetricDimension is min=0.
	MetricDimension []TargetTrackingConfigurationCustomizedMetricSpecificationMetricDimension `hcl:"metric_dimension,block" validate:"min=0"`
	// TargetTrackingConfigurationCustomizedMetricSpecificationMetrics is min=0.
	Metrics []TargetTrackingConfigurationCustomizedMetricSpecificationMetrics `hcl:"metrics,block" validate:"min=0"`
}

type TargetTrackingConfigurationCustomizedMetricSpecificationMetricDimension struct {
	// Name is required.
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// Value is required.
	Value terra.StringValue `hcl:"value,attr" validate:"required"`
}

type TargetTrackingConfigurationCustomizedMetricSpecificationMetrics struct {
	// Expression is optional.
	Expression terra.StringValue `hcl:"expression,attr"`
	// Id is required.
	Id terra.StringValue `hcl:"id,attr" validate:"required"`
	// Label is optional.
	Label terra.StringValue `hcl:"label,attr"`
	// ReturnData is optional.
	ReturnData terra.BoolValue `hcl:"return_data,attr"`
	// TargetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStat is optional.
	MetricStat *TargetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStat `hcl:"metric_stat,block"`
}

type TargetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStat struct {
	// Stat is required.
	Stat terra.StringValue `hcl:"stat,attr" validate:"required"`
	// Unit is optional.
	Unit terra.StringValue `hcl:"unit,attr"`
	// TargetTrackingConfigurationCustomizedMetricSpecification16C72277 is required.
	Metric *TargetTrackingConfigurationCustomizedMetricSpecification16C72277 `hcl:"metric,block" validate:"required"`
}

type TargetTrackingConfigurationCustomizedMetricSpecification16C72277 struct {
	// MetricName is required.
	MetricName terra.StringValue `hcl:"metric_name,attr" validate:"required"`
	// Namespace is required.
	Namespace terra.StringValue `hcl:"namespace,attr" validate:"required"`
	// TargetTrackingConfigurationCustomizedMetricSpecificationB8F12109 is min=0.
	Dimensions []TargetTrackingConfigurationCustomizedMetricSpecificationB8F12109 `hcl:"dimensions,block" validate:"min=0"`
}

type TargetTrackingConfigurationCustomizedMetricSpecificationB8F12109 struct {
	// Name is required.
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// Value is required.
	Value terra.StringValue `hcl:"value,attr" validate:"required"`
}

type TargetTrackingConfigurationPredefinedMetricSpecification struct {
	// PredefinedMetricType is required.
	PredefinedMetricType terra.StringValue `hcl:"predefined_metric_type,attr" validate:"required"`
	// ResourceLabel is optional.
	ResourceLabel terra.StringValue `hcl:"resource_label,attr"`
}

type predictiveScalingConfigurationAttributes struct {
	ref terra.Reference
}

func (psc predictiveScalingConfigurationAttributes) InternalRef() (terra.Reference, error) {
	return psc.ref, nil
}

func (psc predictiveScalingConfigurationAttributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationAttributes {
	return predictiveScalingConfigurationAttributes{ref: ref}
}

func (psc predictiveScalingConfigurationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return psc.ref.InternalTokens()
}

func (psc predictiveScalingConfigurationAttributes) MaxCapacityBreachBehavior() terra.StringValue {
	return terra.ReferenceAsString(psc.ref.Append("max_capacity_breach_behavior"))
}

func (psc predictiveScalingConfigurationAttributes) MaxCapacityBuffer() terra.StringValue {
	return terra.ReferenceAsString(psc.ref.Append("max_capacity_buffer"))
}

func (psc predictiveScalingConfigurationAttributes) Mode() terra.StringValue {
	return terra.ReferenceAsString(psc.ref.Append("mode"))
}

func (psc predictiveScalingConfigurationAttributes) SchedulingBufferTime() terra.StringValue {
	return terra.ReferenceAsString(psc.ref.Append("scheduling_buffer_time"))
}

func (psc predictiveScalingConfigurationAttributes) MetricSpecification() terra.ListValue[predictiveScalingConfigurationMetricSpecificationAttributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecificationAttributes](psc.ref.Append("metric_specification"))
}

type predictiveScalingConfigurationMetricSpecificationAttributes struct {
	ref terra.Reference
}

func (ms predictiveScalingConfigurationMetricSpecificationAttributes) InternalRef() (terra.Reference, error) {
	return ms.ref, nil
}

func (ms predictiveScalingConfigurationMetricSpecificationAttributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecificationAttributes {
	return predictiveScalingConfigurationMetricSpecificationAttributes{ref: ref}
}

func (ms predictiveScalingConfigurationMetricSpecificationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ms.ref.InternalTokens()
}

func (ms predictiveScalingConfigurationMetricSpecificationAttributes) TargetValue() terra.NumberValue {
	return terra.ReferenceAsNumber(ms.ref.Append("target_value"))
}

func (ms predictiveScalingConfigurationMetricSpecificationAttributes) CustomizedCapacityMetricSpecification() terra.ListValue[predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationAttributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationAttributes](ms.ref.Append("customized_capacity_metric_specification"))
}

func (ms predictiveScalingConfigurationMetricSpecificationAttributes) CustomizedLoadMetricSpecification() terra.ListValue[predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationAttributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationAttributes](ms.ref.Append("customized_load_metric_specification"))
}

func (ms predictiveScalingConfigurationMetricSpecificationAttributes) CustomizedScalingMetricSpecification() terra.ListValue[predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationAttributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationAttributes](ms.ref.Append("customized_scaling_metric_specification"))
}

func (ms predictiveScalingConfigurationMetricSpecificationAttributes) PredefinedLoadMetricSpecification() terra.ListValue[predictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecificationAttributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecificationAttributes](ms.ref.Append("predefined_load_metric_specification"))
}

func (ms predictiveScalingConfigurationMetricSpecificationAttributes) PredefinedMetricPairSpecification() terra.ListValue[predictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecificationAttributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecificationAttributes](ms.ref.Append("predefined_metric_pair_specification"))
}

func (ms predictiveScalingConfigurationMetricSpecificationAttributes) PredefinedScalingMetricSpecification() terra.ListValue[predictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecificationAttributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecificationAttributes](ms.ref.Append("predefined_scaling_metric_specification"))
}

type predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationAttributes struct {
	ref terra.Reference
}

func (ccms predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationAttributes) InternalRef() (terra.Reference, error) {
	return ccms.ref, nil
}

func (ccms predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationAttributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationAttributes {
	return predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationAttributes{ref: ref}
}

func (ccms predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ccms.ref.InternalTokens()
}

func (ccms predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationAttributes) MetricDataQueries() terra.ListValue[predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesAttributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesAttributes](ccms.ref.Append("metric_data_queries"))
}

type predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesAttributes struct {
	ref terra.Reference
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesAttributes) InternalRef() (terra.Reference, error) {
	return mdq.ref, nil
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesAttributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesAttributes {
	return predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesAttributes{ref: ref}
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return mdq.ref.InternalTokens()
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesAttributes) Expression() terra.StringValue {
	return terra.ReferenceAsString(mdq.ref.Append("expression"))
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(mdq.ref.Append("id"))
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesAttributes) Label() terra.StringValue {
	return terra.ReferenceAsString(mdq.ref.Append("label"))
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesAttributes) ReturnData() terra.BoolValue {
	return terra.ReferenceAsBool(mdq.ref.Append("return_data"))
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesAttributes) MetricStat() terra.ListValue[predictiveScalingConfigurationMetricSpecification716314D0Attributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecification716314D0Attributes](mdq.ref.Append("metric_stat"))
}

type predictiveScalingConfigurationMetricSpecification716314D0Attributes struct {
	ref terra.Reference
}

func (ms predictiveScalingConfigurationMetricSpecification716314D0Attributes) InternalRef() (terra.Reference, error) {
	return ms.ref, nil
}

func (ms predictiveScalingConfigurationMetricSpecification716314D0Attributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecification716314D0Attributes {
	return predictiveScalingConfigurationMetricSpecification716314D0Attributes{ref: ref}
}

func (ms predictiveScalingConfigurationMetricSpecification716314D0Attributes) InternalTokens() (hclwrite.Tokens, error) {
	return ms.ref.InternalTokens()
}

func (ms predictiveScalingConfigurationMetricSpecification716314D0Attributes) Stat() terra.StringValue {
	return terra.ReferenceAsString(ms.ref.Append("stat"))
}

func (ms predictiveScalingConfigurationMetricSpecification716314D0Attributes) Unit() terra.StringValue {
	return terra.ReferenceAsString(ms.ref.Append("unit"))
}

func (ms predictiveScalingConfigurationMetricSpecification716314D0Attributes) Metric() terra.ListValue[predictiveScalingConfigurationMetricSpecification63A47Dc5Attributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecification63A47Dc5Attributes](ms.ref.Append("metric"))
}

type predictiveScalingConfigurationMetricSpecification63A47Dc5Attributes struct {
	ref terra.Reference
}

func (m predictiveScalingConfigurationMetricSpecification63A47Dc5Attributes) InternalRef() (terra.Reference, error) {
	return m.ref, nil
}

func (m predictiveScalingConfigurationMetricSpecification63A47Dc5Attributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecification63A47Dc5Attributes {
	return predictiveScalingConfigurationMetricSpecification63A47Dc5Attributes{ref: ref}
}

func (m predictiveScalingConfigurationMetricSpecification63A47Dc5Attributes) InternalTokens() (hclwrite.Tokens, error) {
	return m.ref.InternalTokens()
}

func (m predictiveScalingConfigurationMetricSpecification63A47Dc5Attributes) MetricName() terra.StringValue {
	return terra.ReferenceAsString(m.ref.Append("metric_name"))
}

func (m predictiveScalingConfigurationMetricSpecification63A47Dc5Attributes) Namespace() terra.StringValue {
	return terra.ReferenceAsString(m.ref.Append("namespace"))
}

func (m predictiveScalingConfigurationMetricSpecification63A47Dc5Attributes) Dimensions() terra.SetValue[predictiveScalingConfigurationMetricSpecification8Ef8Ae96Attributes] {
	return terra.ReferenceAsSet[predictiveScalingConfigurationMetricSpecification8Ef8Ae96Attributes](m.ref.Append("dimensions"))
}

type predictiveScalingConfigurationMetricSpecification8Ef8Ae96Attributes struct {
	ref terra.Reference
}

func (d predictiveScalingConfigurationMetricSpecification8Ef8Ae96Attributes) InternalRef() (terra.Reference, error) {
	return d.ref, nil
}

func (d predictiveScalingConfigurationMetricSpecification8Ef8Ae96Attributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecification8Ef8Ae96Attributes {
	return predictiveScalingConfigurationMetricSpecification8Ef8Ae96Attributes{ref: ref}
}

func (d predictiveScalingConfigurationMetricSpecification8Ef8Ae96Attributes) InternalTokens() (hclwrite.Tokens, error) {
	return d.ref.InternalTokens()
}

func (d predictiveScalingConfigurationMetricSpecification8Ef8Ae96Attributes) Name() terra.StringValue {
	return terra.ReferenceAsString(d.ref.Append("name"))
}

func (d predictiveScalingConfigurationMetricSpecification8Ef8Ae96Attributes) Value() terra.StringValue {
	return terra.ReferenceAsString(d.ref.Append("value"))
}

type predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationAttributes struct {
	ref terra.Reference
}

func (clms predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationAttributes) InternalRef() (terra.Reference, error) {
	return clms.ref, nil
}

func (clms predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationAttributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationAttributes {
	return predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationAttributes{ref: ref}
}

func (clms predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return clms.ref.InternalTokens()
}

func (clms predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationAttributes) MetricDataQueries() terra.ListValue[predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesAttributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesAttributes](clms.ref.Append("metric_data_queries"))
}

type predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesAttributes struct {
	ref terra.Reference
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesAttributes) InternalRef() (terra.Reference, error) {
	return mdq.ref, nil
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesAttributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesAttributes {
	return predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesAttributes{ref: ref}
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return mdq.ref.InternalTokens()
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesAttributes) Expression() terra.StringValue {
	return terra.ReferenceAsString(mdq.ref.Append("expression"))
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(mdq.ref.Append("id"))
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesAttributes) Label() terra.StringValue {
	return terra.ReferenceAsString(mdq.ref.Append("label"))
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesAttributes) ReturnData() terra.BoolValue {
	return terra.ReferenceAsBool(mdq.ref.Append("return_data"))
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesAttributes) MetricStat() terra.ListValue[predictiveScalingConfigurationMetricSpecificationB67D72FeAttributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecificationB67D72FeAttributes](mdq.ref.Append("metric_stat"))
}

type predictiveScalingConfigurationMetricSpecificationB67D72FeAttributes struct {
	ref terra.Reference
}

func (ms predictiveScalingConfigurationMetricSpecificationB67D72FeAttributes) InternalRef() (terra.Reference, error) {
	return ms.ref, nil
}

func (ms predictiveScalingConfigurationMetricSpecificationB67D72FeAttributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecificationB67D72FeAttributes {
	return predictiveScalingConfigurationMetricSpecificationB67D72FeAttributes{ref: ref}
}

func (ms predictiveScalingConfigurationMetricSpecificationB67D72FeAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ms.ref.InternalTokens()
}

func (ms predictiveScalingConfigurationMetricSpecificationB67D72FeAttributes) Stat() terra.StringValue {
	return terra.ReferenceAsString(ms.ref.Append("stat"))
}

func (ms predictiveScalingConfigurationMetricSpecificationB67D72FeAttributes) Unit() terra.StringValue {
	return terra.ReferenceAsString(ms.ref.Append("unit"))
}

func (ms predictiveScalingConfigurationMetricSpecificationB67D72FeAttributes) Metric() terra.ListValue[predictiveScalingConfigurationMetricSpecification5Ec745A9Attributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecification5Ec745A9Attributes](ms.ref.Append("metric"))
}

type predictiveScalingConfigurationMetricSpecification5Ec745A9Attributes struct {
	ref terra.Reference
}

func (m predictiveScalingConfigurationMetricSpecification5Ec745A9Attributes) InternalRef() (terra.Reference, error) {
	return m.ref, nil
}

func (m predictiveScalingConfigurationMetricSpecification5Ec745A9Attributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecification5Ec745A9Attributes {
	return predictiveScalingConfigurationMetricSpecification5Ec745A9Attributes{ref: ref}
}

func (m predictiveScalingConfigurationMetricSpecification5Ec745A9Attributes) InternalTokens() (hclwrite.Tokens, error) {
	return m.ref.InternalTokens()
}

func (m predictiveScalingConfigurationMetricSpecification5Ec745A9Attributes) MetricName() terra.StringValue {
	return terra.ReferenceAsString(m.ref.Append("metric_name"))
}

func (m predictiveScalingConfigurationMetricSpecification5Ec745A9Attributes) Namespace() terra.StringValue {
	return terra.ReferenceAsString(m.ref.Append("namespace"))
}

func (m predictiveScalingConfigurationMetricSpecification5Ec745A9Attributes) Dimensions() terra.SetValue[predictiveScalingConfigurationMetricSpecificationA484Bbb1Attributes] {
	return terra.ReferenceAsSet[predictiveScalingConfigurationMetricSpecificationA484Bbb1Attributes](m.ref.Append("dimensions"))
}

type predictiveScalingConfigurationMetricSpecificationA484Bbb1Attributes struct {
	ref terra.Reference
}

func (d predictiveScalingConfigurationMetricSpecificationA484Bbb1Attributes) InternalRef() (terra.Reference, error) {
	return d.ref, nil
}

func (d predictiveScalingConfigurationMetricSpecificationA484Bbb1Attributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecificationA484Bbb1Attributes {
	return predictiveScalingConfigurationMetricSpecificationA484Bbb1Attributes{ref: ref}
}

func (d predictiveScalingConfigurationMetricSpecificationA484Bbb1Attributes) InternalTokens() (hclwrite.Tokens, error) {
	return d.ref.InternalTokens()
}

func (d predictiveScalingConfigurationMetricSpecificationA484Bbb1Attributes) Name() terra.StringValue {
	return terra.ReferenceAsString(d.ref.Append("name"))
}

func (d predictiveScalingConfigurationMetricSpecificationA484Bbb1Attributes) Value() terra.StringValue {
	return terra.ReferenceAsString(d.ref.Append("value"))
}

type predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationAttributes struct {
	ref terra.Reference
}

func (csms predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationAttributes) InternalRef() (terra.Reference, error) {
	return csms.ref, nil
}

func (csms predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationAttributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationAttributes {
	return predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationAttributes{ref: ref}
}

func (csms predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return csms.ref.InternalTokens()
}

func (csms predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationAttributes) MetricDataQueries() terra.ListValue[predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesAttributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesAttributes](csms.ref.Append("metric_data_queries"))
}

type predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesAttributes struct {
	ref terra.Reference
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesAttributes) InternalRef() (terra.Reference, error) {
	return mdq.ref, nil
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesAttributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesAttributes {
	return predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesAttributes{ref: ref}
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return mdq.ref.InternalTokens()
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesAttributes) Expression() terra.StringValue {
	return terra.ReferenceAsString(mdq.ref.Append("expression"))
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(mdq.ref.Append("id"))
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesAttributes) Label() terra.StringValue {
	return terra.ReferenceAsString(mdq.ref.Append("label"))
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesAttributes) ReturnData() terra.BoolValue {
	return terra.ReferenceAsBool(mdq.ref.Append("return_data"))
}

func (mdq predictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesAttributes) MetricStat() terra.ListValue[predictiveScalingConfigurationMetricSpecification61E4D6D6Attributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecification61E4D6D6Attributes](mdq.ref.Append("metric_stat"))
}

type predictiveScalingConfigurationMetricSpecification61E4D6D6Attributes struct {
	ref terra.Reference
}

func (ms predictiveScalingConfigurationMetricSpecification61E4D6D6Attributes) InternalRef() (terra.Reference, error) {
	return ms.ref, nil
}

func (ms predictiveScalingConfigurationMetricSpecification61E4D6D6Attributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecification61E4D6D6Attributes {
	return predictiveScalingConfigurationMetricSpecification61E4D6D6Attributes{ref: ref}
}

func (ms predictiveScalingConfigurationMetricSpecification61E4D6D6Attributes) InternalTokens() (hclwrite.Tokens, error) {
	return ms.ref.InternalTokens()
}

func (ms predictiveScalingConfigurationMetricSpecification61E4D6D6Attributes) Stat() terra.StringValue {
	return terra.ReferenceAsString(ms.ref.Append("stat"))
}

func (ms predictiveScalingConfigurationMetricSpecification61E4D6D6Attributes) Unit() terra.StringValue {
	return terra.ReferenceAsString(ms.ref.Append("unit"))
}

func (ms predictiveScalingConfigurationMetricSpecification61E4D6D6Attributes) Metric() terra.ListValue[predictiveScalingConfigurationMetricSpecification7A152D67Attributes] {
	return terra.ReferenceAsList[predictiveScalingConfigurationMetricSpecification7A152D67Attributes](ms.ref.Append("metric"))
}

type predictiveScalingConfigurationMetricSpecification7A152D67Attributes struct {
	ref terra.Reference
}

func (m predictiveScalingConfigurationMetricSpecification7A152D67Attributes) InternalRef() (terra.Reference, error) {
	return m.ref, nil
}

func (m predictiveScalingConfigurationMetricSpecification7A152D67Attributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecification7A152D67Attributes {
	return predictiveScalingConfigurationMetricSpecification7A152D67Attributes{ref: ref}
}

func (m predictiveScalingConfigurationMetricSpecification7A152D67Attributes) InternalTokens() (hclwrite.Tokens, error) {
	return m.ref.InternalTokens()
}

func (m predictiveScalingConfigurationMetricSpecification7A152D67Attributes) MetricName() terra.StringValue {
	return terra.ReferenceAsString(m.ref.Append("metric_name"))
}

func (m predictiveScalingConfigurationMetricSpecification7A152D67Attributes) Namespace() terra.StringValue {
	return terra.ReferenceAsString(m.ref.Append("namespace"))
}

func (m predictiveScalingConfigurationMetricSpecification7A152D67Attributes) Dimensions() terra.SetValue[predictiveScalingConfigurationMetricSpecification56Ac0CaeAttributes] {
	return terra.ReferenceAsSet[predictiveScalingConfigurationMetricSpecification56Ac0CaeAttributes](m.ref.Append("dimensions"))
}

type predictiveScalingConfigurationMetricSpecification56Ac0CaeAttributes struct {
	ref terra.Reference
}

func (d predictiveScalingConfigurationMetricSpecification56Ac0CaeAttributes) InternalRef() (terra.Reference, error) {
	return d.ref, nil
}

func (d predictiveScalingConfigurationMetricSpecification56Ac0CaeAttributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecification56Ac0CaeAttributes {
	return predictiveScalingConfigurationMetricSpecification56Ac0CaeAttributes{ref: ref}
}

func (d predictiveScalingConfigurationMetricSpecification56Ac0CaeAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return d.ref.InternalTokens()
}

func (d predictiveScalingConfigurationMetricSpecification56Ac0CaeAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(d.ref.Append("name"))
}

func (d predictiveScalingConfigurationMetricSpecification56Ac0CaeAttributes) Value() terra.StringValue {
	return terra.ReferenceAsString(d.ref.Append("value"))
}

type predictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecificationAttributes struct {
	ref terra.Reference
}

func (plms predictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecificationAttributes) InternalRef() (terra.Reference, error) {
	return plms.ref, nil
}

func (plms predictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecificationAttributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecificationAttributes {
	return predictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecificationAttributes{ref: ref}
}

func (plms predictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecificationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return plms.ref.InternalTokens()
}

func (plms predictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecificationAttributes) PredefinedMetricType() terra.StringValue {
	return terra.ReferenceAsString(plms.ref.Append("predefined_metric_type"))
}

func (plms predictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecificationAttributes) ResourceLabel() terra.StringValue {
	return terra.ReferenceAsString(plms.ref.Append("resource_label"))
}

type predictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecificationAttributes struct {
	ref terra.Reference
}

func (pmps predictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecificationAttributes) InternalRef() (terra.Reference, error) {
	return pmps.ref, nil
}

func (pmps predictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecificationAttributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecificationAttributes {
	return predictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecificationAttributes{ref: ref}
}

func (pmps predictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecificationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return pmps.ref.InternalTokens()
}

func (pmps predictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecificationAttributes) PredefinedMetricType() terra.StringValue {
	return terra.ReferenceAsString(pmps.ref.Append("predefined_metric_type"))
}

func (pmps predictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecificationAttributes) ResourceLabel() terra.StringValue {
	return terra.ReferenceAsString(pmps.ref.Append("resource_label"))
}

type predictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecificationAttributes struct {
	ref terra.Reference
}

func (psms predictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecificationAttributes) InternalRef() (terra.Reference, error) {
	return psms.ref, nil
}

func (psms predictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecificationAttributes) InternalWithRef(ref terra.Reference) predictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecificationAttributes {
	return predictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecificationAttributes{ref: ref}
}

func (psms predictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecificationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return psms.ref.InternalTokens()
}

func (psms predictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecificationAttributes) PredefinedMetricType() terra.StringValue {
	return terra.ReferenceAsString(psms.ref.Append("predefined_metric_type"))
}

func (psms predictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecificationAttributes) ResourceLabel() terra.StringValue {
	return terra.ReferenceAsString(psms.ref.Append("resource_label"))
}

type stepAdjustmentAttributes struct {
	ref terra.Reference
}

func (sa stepAdjustmentAttributes) InternalRef() (terra.Reference, error) {
	return sa.ref, nil
}

func (sa stepAdjustmentAttributes) InternalWithRef(ref terra.Reference) stepAdjustmentAttributes {
	return stepAdjustmentAttributes{ref: ref}
}

func (sa stepAdjustmentAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return sa.ref.InternalTokens()
}

func (sa stepAdjustmentAttributes) MetricIntervalLowerBound() terra.StringValue {
	return terra.ReferenceAsString(sa.ref.Append("metric_interval_lower_bound"))
}

func (sa stepAdjustmentAttributes) MetricIntervalUpperBound() terra.StringValue {
	return terra.ReferenceAsString(sa.ref.Append("metric_interval_upper_bound"))
}

func (sa stepAdjustmentAttributes) ScalingAdjustment() terra.NumberValue {
	return terra.ReferenceAsNumber(sa.ref.Append("scaling_adjustment"))
}

type targetTrackingConfigurationAttributes struct {
	ref terra.Reference
}

func (ttc targetTrackingConfigurationAttributes) InternalRef() (terra.Reference, error) {
	return ttc.ref, nil
}

func (ttc targetTrackingConfigurationAttributes) InternalWithRef(ref terra.Reference) targetTrackingConfigurationAttributes {
	return targetTrackingConfigurationAttributes{ref: ref}
}

func (ttc targetTrackingConfigurationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ttc.ref.InternalTokens()
}

func (ttc targetTrackingConfigurationAttributes) DisableScaleIn() terra.BoolValue {
	return terra.ReferenceAsBool(ttc.ref.Append("disable_scale_in"))
}

func (ttc targetTrackingConfigurationAttributes) TargetValue() terra.NumberValue {
	return terra.ReferenceAsNumber(ttc.ref.Append("target_value"))
}

func (ttc targetTrackingConfigurationAttributes) CustomizedMetricSpecification() terra.ListValue[targetTrackingConfigurationCustomizedMetricSpecificationAttributes] {
	return terra.ReferenceAsList[targetTrackingConfigurationCustomizedMetricSpecificationAttributes](ttc.ref.Append("customized_metric_specification"))
}

func (ttc targetTrackingConfigurationAttributes) PredefinedMetricSpecification() terra.ListValue[targetTrackingConfigurationPredefinedMetricSpecificationAttributes] {
	return terra.ReferenceAsList[targetTrackingConfigurationPredefinedMetricSpecificationAttributes](ttc.ref.Append("predefined_metric_specification"))
}

type targetTrackingConfigurationCustomizedMetricSpecificationAttributes struct {
	ref terra.Reference
}

func (cms targetTrackingConfigurationCustomizedMetricSpecificationAttributes) InternalRef() (terra.Reference, error) {
	return cms.ref, nil
}

func (cms targetTrackingConfigurationCustomizedMetricSpecificationAttributes) InternalWithRef(ref terra.Reference) targetTrackingConfigurationCustomizedMetricSpecificationAttributes {
	return targetTrackingConfigurationCustomizedMetricSpecificationAttributes{ref: ref}
}

func (cms targetTrackingConfigurationCustomizedMetricSpecificationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return cms.ref.InternalTokens()
}

func (cms targetTrackingConfigurationCustomizedMetricSpecificationAttributes) MetricName() terra.StringValue {
	return terra.ReferenceAsString(cms.ref.Append("metric_name"))
}

func (cms targetTrackingConfigurationCustomizedMetricSpecificationAttributes) Namespace() terra.StringValue {
	return terra.ReferenceAsString(cms.ref.Append("namespace"))
}

func (cms targetTrackingConfigurationCustomizedMetricSpecificationAttributes) Statistic() terra.StringValue {
	return terra.ReferenceAsString(cms.ref.Append("statistic"))
}

func (cms targetTrackingConfigurationCustomizedMetricSpecificationAttributes) Unit() terra.StringValue {
	return terra.ReferenceAsString(cms.ref.Append("unit"))
}

func (cms targetTrackingConfigurationCustomizedMetricSpecificationAttributes) MetricDimension() terra.ListValue[targetTrackingConfigurationCustomizedMetricSpecificationMetricDimensionAttributes] {
	return terra.ReferenceAsList[targetTrackingConfigurationCustomizedMetricSpecificationMetricDimensionAttributes](cms.ref.Append("metric_dimension"))
}

func (cms targetTrackingConfigurationCustomizedMetricSpecificationAttributes) Metrics() terra.SetValue[targetTrackingConfigurationCustomizedMetricSpecificationMetricsAttributes] {
	return terra.ReferenceAsSet[targetTrackingConfigurationCustomizedMetricSpecificationMetricsAttributes](cms.ref.Append("metrics"))
}

type targetTrackingConfigurationCustomizedMetricSpecificationMetricDimensionAttributes struct {
	ref terra.Reference
}

func (md targetTrackingConfigurationCustomizedMetricSpecificationMetricDimensionAttributes) InternalRef() (terra.Reference, error) {
	return md.ref, nil
}

func (md targetTrackingConfigurationCustomizedMetricSpecificationMetricDimensionAttributes) InternalWithRef(ref terra.Reference) targetTrackingConfigurationCustomizedMetricSpecificationMetricDimensionAttributes {
	return targetTrackingConfigurationCustomizedMetricSpecificationMetricDimensionAttributes{ref: ref}
}

func (md targetTrackingConfigurationCustomizedMetricSpecificationMetricDimensionAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return md.ref.InternalTokens()
}

func (md targetTrackingConfigurationCustomizedMetricSpecificationMetricDimensionAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(md.ref.Append("name"))
}

func (md targetTrackingConfigurationCustomizedMetricSpecificationMetricDimensionAttributes) Value() terra.StringValue {
	return terra.ReferenceAsString(md.ref.Append("value"))
}

type targetTrackingConfigurationCustomizedMetricSpecificationMetricsAttributes struct {
	ref terra.Reference
}

func (m targetTrackingConfigurationCustomizedMetricSpecificationMetricsAttributes) InternalRef() (terra.Reference, error) {
	return m.ref, nil
}

func (m targetTrackingConfigurationCustomizedMetricSpecificationMetricsAttributes) InternalWithRef(ref terra.Reference) targetTrackingConfigurationCustomizedMetricSpecificationMetricsAttributes {
	return targetTrackingConfigurationCustomizedMetricSpecificationMetricsAttributes{ref: ref}
}

func (m targetTrackingConfigurationCustomizedMetricSpecificationMetricsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return m.ref.InternalTokens()
}

func (m targetTrackingConfigurationCustomizedMetricSpecificationMetricsAttributes) Expression() terra.StringValue {
	return terra.ReferenceAsString(m.ref.Append("expression"))
}

func (m targetTrackingConfigurationCustomizedMetricSpecificationMetricsAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(m.ref.Append("id"))
}

func (m targetTrackingConfigurationCustomizedMetricSpecificationMetricsAttributes) Label() terra.StringValue {
	return terra.ReferenceAsString(m.ref.Append("label"))
}

func (m targetTrackingConfigurationCustomizedMetricSpecificationMetricsAttributes) ReturnData() terra.BoolValue {
	return terra.ReferenceAsBool(m.ref.Append("return_data"))
}

func (m targetTrackingConfigurationCustomizedMetricSpecificationMetricsAttributes) MetricStat() terra.ListValue[targetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStatAttributes] {
	return terra.ReferenceAsList[targetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStatAttributes](m.ref.Append("metric_stat"))
}

type targetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStatAttributes struct {
	ref terra.Reference
}

func (ms targetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStatAttributes) InternalRef() (terra.Reference, error) {
	return ms.ref, nil
}

func (ms targetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStatAttributes) InternalWithRef(ref terra.Reference) targetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStatAttributes {
	return targetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStatAttributes{ref: ref}
}

func (ms targetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStatAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ms.ref.InternalTokens()
}

func (ms targetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStatAttributes) Stat() terra.StringValue {
	return terra.ReferenceAsString(ms.ref.Append("stat"))
}

func (ms targetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStatAttributes) Unit() terra.StringValue {
	return terra.ReferenceAsString(ms.ref.Append("unit"))
}

func (ms targetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStatAttributes) Metric() terra.ListValue[targetTrackingConfigurationCustomizedMetricSpecification16C72277Attributes] {
	return terra.ReferenceAsList[targetTrackingConfigurationCustomizedMetricSpecification16C72277Attributes](ms.ref.Append("metric"))
}

type targetTrackingConfigurationCustomizedMetricSpecification16C72277Attributes struct {
	ref terra.Reference
}

func (m targetTrackingConfigurationCustomizedMetricSpecification16C72277Attributes) InternalRef() (terra.Reference, error) {
	return m.ref, nil
}

func (m targetTrackingConfigurationCustomizedMetricSpecification16C72277Attributes) InternalWithRef(ref terra.Reference) targetTrackingConfigurationCustomizedMetricSpecification16C72277Attributes {
	return targetTrackingConfigurationCustomizedMetricSpecification16C72277Attributes{ref: ref}
}

func (m targetTrackingConfigurationCustomizedMetricSpecification16C72277Attributes) InternalTokens() (hclwrite.Tokens, error) {
	return m.ref.InternalTokens()
}

func (m targetTrackingConfigurationCustomizedMetricSpecification16C72277Attributes) MetricName() terra.StringValue {
	return terra.ReferenceAsString(m.ref.Append("metric_name"))
}

func (m targetTrackingConfigurationCustomizedMetricSpecification16C72277Attributes) Namespace() terra.StringValue {
	return terra.ReferenceAsString(m.ref.Append("namespace"))
}

func (m targetTrackingConfigurationCustomizedMetricSpecification16C72277Attributes) Dimensions() terra.SetValue[targetTrackingConfigurationCustomizedMetricSpecificationB8F12109Attributes] {
	return terra.ReferenceAsSet[targetTrackingConfigurationCustomizedMetricSpecificationB8F12109Attributes](m.ref.Append("dimensions"))
}

type targetTrackingConfigurationCustomizedMetricSpecificationB8F12109Attributes struct {
	ref terra.Reference
}

func (d targetTrackingConfigurationCustomizedMetricSpecificationB8F12109Attributes) InternalRef() (terra.Reference, error) {
	return d.ref, nil
}

func (d targetTrackingConfigurationCustomizedMetricSpecificationB8F12109Attributes) InternalWithRef(ref terra.Reference) targetTrackingConfigurationCustomizedMetricSpecificationB8F12109Attributes {
	return targetTrackingConfigurationCustomizedMetricSpecificationB8F12109Attributes{ref: ref}
}

func (d targetTrackingConfigurationCustomizedMetricSpecificationB8F12109Attributes) InternalTokens() (hclwrite.Tokens, error) {
	return d.ref.InternalTokens()
}

func (d targetTrackingConfigurationCustomizedMetricSpecificationB8F12109Attributes) Name() terra.StringValue {
	return terra.ReferenceAsString(d.ref.Append("name"))
}

func (d targetTrackingConfigurationCustomizedMetricSpecificationB8F12109Attributes) Value() terra.StringValue {
	return terra.ReferenceAsString(d.ref.Append("value"))
}

type targetTrackingConfigurationPredefinedMetricSpecificationAttributes struct {
	ref terra.Reference
}

func (pms targetTrackingConfigurationPredefinedMetricSpecificationAttributes) InternalRef() (terra.Reference, error) {
	return pms.ref, nil
}

func (pms targetTrackingConfigurationPredefinedMetricSpecificationAttributes) InternalWithRef(ref terra.Reference) targetTrackingConfigurationPredefinedMetricSpecificationAttributes {
	return targetTrackingConfigurationPredefinedMetricSpecificationAttributes{ref: ref}
}

func (pms targetTrackingConfigurationPredefinedMetricSpecificationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return pms.ref.InternalTokens()
}

func (pms targetTrackingConfigurationPredefinedMetricSpecificationAttributes) PredefinedMetricType() terra.StringValue {
	return terra.ReferenceAsString(pms.ref.Append("predefined_metric_type"))
}

func (pms targetTrackingConfigurationPredefinedMetricSpecificationAttributes) ResourceLabel() terra.StringValue {
	return terra.ReferenceAsString(pms.ref.Append("resource_label"))
}

type PredictiveScalingConfigurationState struct {
	MaxCapacityBreachBehavior string                                                   `json:"max_capacity_breach_behavior"`
	MaxCapacityBuffer         string                                                   `json:"max_capacity_buffer"`
	Mode                      string                                                   `json:"mode"`
	SchedulingBufferTime      string                                                   `json:"scheduling_buffer_time"`
	MetricSpecification       []PredictiveScalingConfigurationMetricSpecificationState `json:"metric_specification"`
}

type PredictiveScalingConfigurationMetricSpecificationState struct {
	TargetValue                           float64                                                                                       `json:"target_value"`
	CustomizedCapacityMetricSpecification []PredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationState `json:"customized_capacity_metric_specification"`
	CustomizedLoadMetricSpecification     []PredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationState     `json:"customized_load_metric_specification"`
	CustomizedScalingMetricSpecification  []PredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationState  `json:"customized_scaling_metric_specification"`
	PredefinedLoadMetricSpecification     []PredictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecificationState     `json:"predefined_load_metric_specification"`
	PredefinedMetricPairSpecification     []PredictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecificationState     `json:"predefined_metric_pair_specification"`
	PredefinedScalingMetricSpecification  []PredictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecificationState  `json:"predefined_scaling_metric_specification"`
}

type PredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationState struct {
	MetricDataQueries []PredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesState `json:"metric_data_queries"`
}

type PredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesState struct {
	Expression string                                                           `json:"expression"`
	Id         string                                                           `json:"id"`
	Label      string                                                           `json:"label"`
	ReturnData bool                                                             `json:"return_data"`
	MetricStat []PredictiveScalingConfigurationMetricSpecification716314D0State `json:"metric_stat"`
}

type PredictiveScalingConfigurationMetricSpecification716314D0State struct {
	Stat   string                                                           `json:"stat"`
	Unit   string                                                           `json:"unit"`
	Metric []PredictiveScalingConfigurationMetricSpecification63A47Dc5State `json:"metric"`
}

type PredictiveScalingConfigurationMetricSpecification63A47Dc5State struct {
	MetricName string                                                           `json:"metric_name"`
	Namespace  string                                                           `json:"namespace"`
	Dimensions []PredictiveScalingConfigurationMetricSpecification8Ef8Ae96State `json:"dimensions"`
}

type PredictiveScalingConfigurationMetricSpecification8Ef8Ae96State struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type PredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationState struct {
	MetricDataQueries []PredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesState `json:"metric_data_queries"`
}

type PredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesState struct {
	Expression string                                                           `json:"expression"`
	Id         string                                                           `json:"id"`
	Label      string                                                           `json:"label"`
	ReturnData bool                                                             `json:"return_data"`
	MetricStat []PredictiveScalingConfigurationMetricSpecificationB67D72FeState `json:"metric_stat"`
}

type PredictiveScalingConfigurationMetricSpecificationB67D72FeState struct {
	Stat   string                                                           `json:"stat"`
	Unit   string                                                           `json:"unit"`
	Metric []PredictiveScalingConfigurationMetricSpecification5Ec745A9State `json:"metric"`
}

type PredictiveScalingConfigurationMetricSpecification5Ec745A9State struct {
	MetricName string                                                           `json:"metric_name"`
	Namespace  string                                                           `json:"namespace"`
	Dimensions []PredictiveScalingConfigurationMetricSpecificationA484Bbb1State `json:"dimensions"`
}

type PredictiveScalingConfigurationMetricSpecificationA484Bbb1State struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type PredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationState struct {
	MetricDataQueries []PredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesState `json:"metric_data_queries"`
}

type PredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesState struct {
	Expression string                                                           `json:"expression"`
	Id         string                                                           `json:"id"`
	Label      string                                                           `json:"label"`
	ReturnData bool                                                             `json:"return_data"`
	MetricStat []PredictiveScalingConfigurationMetricSpecification61E4D6D6State `json:"metric_stat"`
}

type PredictiveScalingConfigurationMetricSpecification61E4D6D6State struct {
	Stat   string                                                           `json:"stat"`
	Unit   string                                                           `json:"unit"`
	Metric []PredictiveScalingConfigurationMetricSpecification7A152D67State `json:"metric"`
}

type PredictiveScalingConfigurationMetricSpecification7A152D67State struct {
	MetricName string                                                           `json:"metric_name"`
	Namespace  string                                                           `json:"namespace"`
	Dimensions []PredictiveScalingConfigurationMetricSpecification56Ac0CaeState `json:"dimensions"`
}

type PredictiveScalingConfigurationMetricSpecification56Ac0CaeState struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type PredictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecificationState struct {
	PredefinedMetricType string `json:"predefined_metric_type"`
	ResourceLabel        string `json:"resource_label"`
}

type PredictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecificationState struct {
	PredefinedMetricType string `json:"predefined_metric_type"`
	ResourceLabel        string `json:"resource_label"`
}

type PredictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecificationState struct {
	PredefinedMetricType string `json:"predefined_metric_type"`
	ResourceLabel        string `json:"resource_label"`
}

type StepAdjustmentState struct {
	MetricIntervalLowerBound string  `json:"metric_interval_lower_bound"`
	MetricIntervalUpperBound string  `json:"metric_interval_upper_bound"`
	ScalingAdjustment        float64 `json:"scaling_adjustment"`
}

type TargetTrackingConfigurationState struct {
	DisableScaleIn                bool                                                            `json:"disable_scale_in"`
	TargetValue                   float64                                                         `json:"target_value"`
	CustomizedMetricSpecification []TargetTrackingConfigurationCustomizedMetricSpecificationState `json:"customized_metric_specification"`
	PredefinedMetricSpecification []TargetTrackingConfigurationPredefinedMetricSpecificationState `json:"predefined_metric_specification"`
}

type TargetTrackingConfigurationCustomizedMetricSpecificationState struct {
	MetricName      string                                                                         `json:"metric_name"`
	Namespace       string                                                                         `json:"namespace"`
	Statistic       string                                                                         `json:"statistic"`
	Unit            string                                                                         `json:"unit"`
	MetricDimension []TargetTrackingConfigurationCustomizedMetricSpecificationMetricDimensionState `json:"metric_dimension"`
	Metrics         []TargetTrackingConfigurationCustomizedMetricSpecificationMetricsState         `json:"metrics"`
}

type TargetTrackingConfigurationCustomizedMetricSpecificationMetricDimensionState struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type TargetTrackingConfigurationCustomizedMetricSpecificationMetricsState struct {
	Expression string                                                                           `json:"expression"`
	Id         string                                                                           `json:"id"`
	Label      string                                                                           `json:"label"`
	ReturnData bool                                                                             `json:"return_data"`
	MetricStat []TargetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStatState `json:"metric_stat"`
}

type TargetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStatState struct {
	Stat   string                                                                  `json:"stat"`
	Unit   string                                                                  `json:"unit"`
	Metric []TargetTrackingConfigurationCustomizedMetricSpecification16C72277State `json:"metric"`
}

type TargetTrackingConfigurationCustomizedMetricSpecification16C72277State struct {
	MetricName string                                                                  `json:"metric_name"`
	Namespace  string                                                                  `json:"namespace"`
	Dimensions []TargetTrackingConfigurationCustomizedMetricSpecificationB8F12109State `json:"dimensions"`
}

type TargetTrackingConfigurationCustomizedMetricSpecificationB8F12109State struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type TargetTrackingConfigurationPredefinedMetricSpecificationState struct {
	PredefinedMetricType string `json:"predefined_metric_type"`
	ResourceLabel        string `json:"resource_label"`
}
