// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_launch_template

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type DataFilter struct {
	// Name is required.
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// Values is required.
	Values terra.ListValue[terra.StringValue] `hcl:"values,attr" validate:"required"`
}

type DataTimeouts struct {
	// Read is optional.
	Read terra.StringValue `hcl:"read,attr"`
}

type DatablockDeviceMappingsAttributes struct {
	ref terra.Reference
}

func (bdm DatablockDeviceMappingsAttributes) InternalRef() (terra.Reference, error) {
	return bdm.ref, nil
}

func (bdm DatablockDeviceMappingsAttributes) InternalWithRef(ref terra.Reference) DatablockDeviceMappingsAttributes {
	return DatablockDeviceMappingsAttributes{ref: ref}
}

func (bdm DatablockDeviceMappingsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return bdm.ref.InternalTokens()
}

func (bdm DatablockDeviceMappingsAttributes) DeviceName() terra.StringValue {
	return terra.ReferenceAsString(bdm.ref.Append("device_name"))
}

func (bdm DatablockDeviceMappingsAttributes) NoDevice() terra.StringValue {
	return terra.ReferenceAsString(bdm.ref.Append("no_device"))
}

func (bdm DatablockDeviceMappingsAttributes) VirtualName() terra.StringValue {
	return terra.ReferenceAsString(bdm.ref.Append("virtual_name"))
}

func (bdm DatablockDeviceMappingsAttributes) Ebs() terra.ListValue[DatablockDeviceMappingsEbsAttributes] {
	return terra.ReferenceAsList[DatablockDeviceMappingsEbsAttributes](bdm.ref.Append("ebs"))
}

type DatablockDeviceMappingsEbsAttributes struct {
	ref terra.Reference
}

func (e DatablockDeviceMappingsEbsAttributes) InternalRef() (terra.Reference, error) {
	return e.ref, nil
}

func (e DatablockDeviceMappingsEbsAttributes) InternalWithRef(ref terra.Reference) DatablockDeviceMappingsEbsAttributes {
	return DatablockDeviceMappingsEbsAttributes{ref: ref}
}

func (e DatablockDeviceMappingsEbsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return e.ref.InternalTokens()
}

func (e DatablockDeviceMappingsEbsAttributes) DeleteOnTermination() terra.StringValue {
	return terra.ReferenceAsString(e.ref.Append("delete_on_termination"))
}

func (e DatablockDeviceMappingsEbsAttributes) Encrypted() terra.StringValue {
	return terra.ReferenceAsString(e.ref.Append("encrypted"))
}

func (e DatablockDeviceMappingsEbsAttributes) Iops() terra.NumberValue {
	return terra.ReferenceAsNumber(e.ref.Append("iops"))
}

func (e DatablockDeviceMappingsEbsAttributes) KmsKeyId() terra.StringValue {
	return terra.ReferenceAsString(e.ref.Append("kms_key_id"))
}

func (e DatablockDeviceMappingsEbsAttributes) SnapshotId() terra.StringValue {
	return terra.ReferenceAsString(e.ref.Append("snapshot_id"))
}

func (e DatablockDeviceMappingsEbsAttributes) Throughput() terra.NumberValue {
	return terra.ReferenceAsNumber(e.ref.Append("throughput"))
}

func (e DatablockDeviceMappingsEbsAttributes) VolumeSize() terra.NumberValue {
	return terra.ReferenceAsNumber(e.ref.Append("volume_size"))
}

func (e DatablockDeviceMappingsEbsAttributes) VolumeType() terra.StringValue {
	return terra.ReferenceAsString(e.ref.Append("volume_type"))
}

type DatacapacityReservationSpecificationAttributes struct {
	ref terra.Reference
}

func (crs DatacapacityReservationSpecificationAttributes) InternalRef() (terra.Reference, error) {
	return crs.ref, nil
}

func (crs DatacapacityReservationSpecificationAttributes) InternalWithRef(ref terra.Reference) DatacapacityReservationSpecificationAttributes {
	return DatacapacityReservationSpecificationAttributes{ref: ref}
}

func (crs DatacapacityReservationSpecificationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return crs.ref.InternalTokens()
}

func (crs DatacapacityReservationSpecificationAttributes) CapacityReservationPreference() terra.StringValue {
	return terra.ReferenceAsString(crs.ref.Append("capacity_reservation_preference"))
}

func (crs DatacapacityReservationSpecificationAttributes) CapacityReservationTarget() terra.ListValue[DatacapacityReservationSpecificationCapacityReservationTargetAttributes] {
	return terra.ReferenceAsList[DatacapacityReservationSpecificationCapacityReservationTargetAttributes](crs.ref.Append("capacity_reservation_target"))
}

type DatacapacityReservationSpecificationCapacityReservationTargetAttributes struct {
	ref terra.Reference
}

func (crt DatacapacityReservationSpecificationCapacityReservationTargetAttributes) InternalRef() (terra.Reference, error) {
	return crt.ref, nil
}

func (crt DatacapacityReservationSpecificationCapacityReservationTargetAttributes) InternalWithRef(ref terra.Reference) DatacapacityReservationSpecificationCapacityReservationTargetAttributes {
	return DatacapacityReservationSpecificationCapacityReservationTargetAttributes{ref: ref}
}

func (crt DatacapacityReservationSpecificationCapacityReservationTargetAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return crt.ref.InternalTokens()
}

func (crt DatacapacityReservationSpecificationCapacityReservationTargetAttributes) CapacityReservationId() terra.StringValue {
	return terra.ReferenceAsString(crt.ref.Append("capacity_reservation_id"))
}

func (crt DatacapacityReservationSpecificationCapacityReservationTargetAttributes) CapacityReservationResourceGroupArn() terra.StringValue {
	return terra.ReferenceAsString(crt.ref.Append("capacity_reservation_resource_group_arn"))
}

type DatacpuOptionsAttributes struct {
	ref terra.Reference
}

func (co DatacpuOptionsAttributes) InternalRef() (terra.Reference, error) {
	return co.ref, nil
}

func (co DatacpuOptionsAttributes) InternalWithRef(ref terra.Reference) DatacpuOptionsAttributes {
	return DatacpuOptionsAttributes{ref: ref}
}

func (co DatacpuOptionsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return co.ref.InternalTokens()
}

func (co DatacpuOptionsAttributes) AmdSevSnp() terra.StringValue {
	return terra.ReferenceAsString(co.ref.Append("amd_sev_snp"))
}

func (co DatacpuOptionsAttributes) CoreCount() terra.NumberValue {
	return terra.ReferenceAsNumber(co.ref.Append("core_count"))
}

func (co DatacpuOptionsAttributes) ThreadsPerCore() terra.NumberValue {
	return terra.ReferenceAsNumber(co.ref.Append("threads_per_core"))
}

type DatacreditSpecificationAttributes struct {
	ref terra.Reference
}

func (cs DatacreditSpecificationAttributes) InternalRef() (terra.Reference, error) {
	return cs.ref, nil
}

func (cs DatacreditSpecificationAttributes) InternalWithRef(ref terra.Reference) DatacreditSpecificationAttributes {
	return DatacreditSpecificationAttributes{ref: ref}
}

func (cs DatacreditSpecificationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return cs.ref.InternalTokens()
}

func (cs DatacreditSpecificationAttributes) CpuCredits() terra.StringValue {
	return terra.ReferenceAsString(cs.ref.Append("cpu_credits"))
}

type DataelasticGpuSpecificationsAttributes struct {
	ref terra.Reference
}

func (egs DataelasticGpuSpecificationsAttributes) InternalRef() (terra.Reference, error) {
	return egs.ref, nil
}

func (egs DataelasticGpuSpecificationsAttributes) InternalWithRef(ref terra.Reference) DataelasticGpuSpecificationsAttributes {
	return DataelasticGpuSpecificationsAttributes{ref: ref}
}

func (egs DataelasticGpuSpecificationsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return egs.ref.InternalTokens()
}

func (egs DataelasticGpuSpecificationsAttributes) Type() terra.StringValue {
	return terra.ReferenceAsString(egs.ref.Append("type"))
}

type DataelasticInferenceAcceleratorAttributes struct {
	ref terra.Reference
}

func (eia DataelasticInferenceAcceleratorAttributes) InternalRef() (terra.Reference, error) {
	return eia.ref, nil
}

func (eia DataelasticInferenceAcceleratorAttributes) InternalWithRef(ref terra.Reference) DataelasticInferenceAcceleratorAttributes {
	return DataelasticInferenceAcceleratorAttributes{ref: ref}
}

func (eia DataelasticInferenceAcceleratorAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return eia.ref.InternalTokens()
}

func (eia DataelasticInferenceAcceleratorAttributes) Type() terra.StringValue {
	return terra.ReferenceAsString(eia.ref.Append("type"))
}

type DataenclaveOptionsAttributes struct {
	ref terra.Reference
}

func (eo DataenclaveOptionsAttributes) InternalRef() (terra.Reference, error) {
	return eo.ref, nil
}

func (eo DataenclaveOptionsAttributes) InternalWithRef(ref terra.Reference) DataenclaveOptionsAttributes {
	return DataenclaveOptionsAttributes{ref: ref}
}

func (eo DataenclaveOptionsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return eo.ref.InternalTokens()
}

func (eo DataenclaveOptionsAttributes) Enabled() terra.BoolValue {
	return terra.ReferenceAsBool(eo.ref.Append("enabled"))
}

type DatahibernationOptionsAttributes struct {
	ref terra.Reference
}

func (ho DatahibernationOptionsAttributes) InternalRef() (terra.Reference, error) {
	return ho.ref, nil
}

func (ho DatahibernationOptionsAttributes) InternalWithRef(ref terra.Reference) DatahibernationOptionsAttributes {
	return DatahibernationOptionsAttributes{ref: ref}
}

func (ho DatahibernationOptionsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ho.ref.InternalTokens()
}

func (ho DatahibernationOptionsAttributes) Configured() terra.BoolValue {
	return terra.ReferenceAsBool(ho.ref.Append("configured"))
}

type DataiamInstanceProfileAttributes struct {
	ref terra.Reference
}

func (iip DataiamInstanceProfileAttributes) InternalRef() (terra.Reference, error) {
	return iip.ref, nil
}

func (iip DataiamInstanceProfileAttributes) InternalWithRef(ref terra.Reference) DataiamInstanceProfileAttributes {
	return DataiamInstanceProfileAttributes{ref: ref}
}

func (iip DataiamInstanceProfileAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return iip.ref.InternalTokens()
}

func (iip DataiamInstanceProfileAttributes) Arn() terra.StringValue {
	return terra.ReferenceAsString(iip.ref.Append("arn"))
}

func (iip DataiamInstanceProfileAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(iip.ref.Append("name"))
}

type DatainstanceMarketOptionsAttributes struct {
	ref terra.Reference
}

func (imo DatainstanceMarketOptionsAttributes) InternalRef() (terra.Reference, error) {
	return imo.ref, nil
}

func (imo DatainstanceMarketOptionsAttributes) InternalWithRef(ref terra.Reference) DatainstanceMarketOptionsAttributes {
	return DatainstanceMarketOptionsAttributes{ref: ref}
}

func (imo DatainstanceMarketOptionsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return imo.ref.InternalTokens()
}

func (imo DatainstanceMarketOptionsAttributes) MarketType() terra.StringValue {
	return terra.ReferenceAsString(imo.ref.Append("market_type"))
}

func (imo DatainstanceMarketOptionsAttributes) SpotOptions() terra.ListValue[DatainstanceMarketOptionsSpotOptionsAttributes] {
	return terra.ReferenceAsList[DatainstanceMarketOptionsSpotOptionsAttributes](imo.ref.Append("spot_options"))
}

type DatainstanceMarketOptionsSpotOptionsAttributes struct {
	ref terra.Reference
}

func (so DatainstanceMarketOptionsSpotOptionsAttributes) InternalRef() (terra.Reference, error) {
	return so.ref, nil
}

func (so DatainstanceMarketOptionsSpotOptionsAttributes) InternalWithRef(ref terra.Reference) DatainstanceMarketOptionsSpotOptionsAttributes {
	return DatainstanceMarketOptionsSpotOptionsAttributes{ref: ref}
}

func (so DatainstanceMarketOptionsSpotOptionsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return so.ref.InternalTokens()
}

func (so DatainstanceMarketOptionsSpotOptionsAttributes) BlockDurationMinutes() terra.NumberValue {
	return terra.ReferenceAsNumber(so.ref.Append("block_duration_minutes"))
}

func (so DatainstanceMarketOptionsSpotOptionsAttributes) InstanceInterruptionBehavior() terra.StringValue {
	return terra.ReferenceAsString(so.ref.Append("instance_interruption_behavior"))
}

func (so DatainstanceMarketOptionsSpotOptionsAttributes) MaxPrice() terra.StringValue {
	return terra.ReferenceAsString(so.ref.Append("max_price"))
}

func (so DatainstanceMarketOptionsSpotOptionsAttributes) SpotInstanceType() terra.StringValue {
	return terra.ReferenceAsString(so.ref.Append("spot_instance_type"))
}

func (so DatainstanceMarketOptionsSpotOptionsAttributes) ValidUntil() terra.StringValue {
	return terra.ReferenceAsString(so.ref.Append("valid_until"))
}

type DatainstanceRequirementsAttributes struct {
	ref terra.Reference
}

func (ir DatainstanceRequirementsAttributes) InternalRef() (terra.Reference, error) {
	return ir.ref, nil
}

func (ir DatainstanceRequirementsAttributes) InternalWithRef(ref terra.Reference) DatainstanceRequirementsAttributes {
	return DatainstanceRequirementsAttributes{ref: ref}
}

func (ir DatainstanceRequirementsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ir.ref.InternalTokens()
}

func (ir DatainstanceRequirementsAttributes) AcceleratorManufacturers() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](ir.ref.Append("accelerator_manufacturers"))
}

func (ir DatainstanceRequirementsAttributes) AcceleratorNames() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](ir.ref.Append("accelerator_names"))
}

func (ir DatainstanceRequirementsAttributes) AcceleratorTypes() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](ir.ref.Append("accelerator_types"))
}

func (ir DatainstanceRequirementsAttributes) AllowedInstanceTypes() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](ir.ref.Append("allowed_instance_types"))
}

func (ir DatainstanceRequirementsAttributes) BareMetal() terra.StringValue {
	return terra.ReferenceAsString(ir.ref.Append("bare_metal"))
}

func (ir DatainstanceRequirementsAttributes) BurstablePerformance() terra.StringValue {
	return terra.ReferenceAsString(ir.ref.Append("burstable_performance"))
}

func (ir DatainstanceRequirementsAttributes) CpuManufacturers() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](ir.ref.Append("cpu_manufacturers"))
}

func (ir DatainstanceRequirementsAttributes) ExcludedInstanceTypes() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](ir.ref.Append("excluded_instance_types"))
}

func (ir DatainstanceRequirementsAttributes) InstanceGenerations() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](ir.ref.Append("instance_generations"))
}

func (ir DatainstanceRequirementsAttributes) LocalStorage() terra.StringValue {
	return terra.ReferenceAsString(ir.ref.Append("local_storage"))
}

func (ir DatainstanceRequirementsAttributes) LocalStorageTypes() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](ir.ref.Append("local_storage_types"))
}

func (ir DatainstanceRequirementsAttributes) OnDemandMaxPricePercentageOverLowestPrice() terra.NumberValue {
	return terra.ReferenceAsNumber(ir.ref.Append("on_demand_max_price_percentage_over_lowest_price"))
}

func (ir DatainstanceRequirementsAttributes) RequireHibernateSupport() terra.BoolValue {
	return terra.ReferenceAsBool(ir.ref.Append("require_hibernate_support"))
}

func (ir DatainstanceRequirementsAttributes) SpotMaxPricePercentageOverLowestPrice() terra.NumberValue {
	return terra.ReferenceAsNumber(ir.ref.Append("spot_max_price_percentage_over_lowest_price"))
}

func (ir DatainstanceRequirementsAttributes) AcceleratorCount() terra.ListValue[DatainstanceRequirementsAcceleratorCountAttributes] {
	return terra.ReferenceAsList[DatainstanceRequirementsAcceleratorCountAttributes](ir.ref.Append("accelerator_count"))
}

func (ir DatainstanceRequirementsAttributes) AcceleratorTotalMemoryMib() terra.ListValue[DatainstanceRequirementsAcceleratorTotalMemoryMibAttributes] {
	return terra.ReferenceAsList[DatainstanceRequirementsAcceleratorTotalMemoryMibAttributes](ir.ref.Append("accelerator_total_memory_mib"))
}

func (ir DatainstanceRequirementsAttributes) BaselineEbsBandwidthMbps() terra.ListValue[DatainstanceRequirementsBaselineEbsBandwidthMbpsAttributes] {
	return terra.ReferenceAsList[DatainstanceRequirementsBaselineEbsBandwidthMbpsAttributes](ir.ref.Append("baseline_ebs_bandwidth_mbps"))
}

func (ir DatainstanceRequirementsAttributes) MemoryGibPerVcpu() terra.ListValue[DatainstanceRequirementsMemoryGibPerVcpuAttributes] {
	return terra.ReferenceAsList[DatainstanceRequirementsMemoryGibPerVcpuAttributes](ir.ref.Append("memory_gib_per_vcpu"))
}

func (ir DatainstanceRequirementsAttributes) MemoryMib() terra.ListValue[DatainstanceRequirementsMemoryMibAttributes] {
	return terra.ReferenceAsList[DatainstanceRequirementsMemoryMibAttributes](ir.ref.Append("memory_mib"))
}

func (ir DatainstanceRequirementsAttributes) NetworkBandwidthGbps() terra.ListValue[DatainstanceRequirementsNetworkBandwidthGbpsAttributes] {
	return terra.ReferenceAsList[DatainstanceRequirementsNetworkBandwidthGbpsAttributes](ir.ref.Append("network_bandwidth_gbps"))
}

func (ir DatainstanceRequirementsAttributes) NetworkInterfaceCount() terra.ListValue[DatainstanceRequirementsNetworkInterfaceCountAttributes] {
	return terra.ReferenceAsList[DatainstanceRequirementsNetworkInterfaceCountAttributes](ir.ref.Append("network_interface_count"))
}

func (ir DatainstanceRequirementsAttributes) TotalLocalStorageGb() terra.ListValue[DatainstanceRequirementsTotalLocalStorageGbAttributes] {
	return terra.ReferenceAsList[DatainstanceRequirementsTotalLocalStorageGbAttributes](ir.ref.Append("total_local_storage_gb"))
}

func (ir DatainstanceRequirementsAttributes) VcpuCount() terra.ListValue[DatainstanceRequirementsVcpuCountAttributes] {
	return terra.ReferenceAsList[DatainstanceRequirementsVcpuCountAttributes](ir.ref.Append("vcpu_count"))
}

type DatainstanceRequirementsAcceleratorCountAttributes struct {
	ref terra.Reference
}

func (ac DatainstanceRequirementsAcceleratorCountAttributes) InternalRef() (terra.Reference, error) {
	return ac.ref, nil
}

func (ac DatainstanceRequirementsAcceleratorCountAttributes) InternalWithRef(ref terra.Reference) DatainstanceRequirementsAcceleratorCountAttributes {
	return DatainstanceRequirementsAcceleratorCountAttributes{ref: ref}
}

func (ac DatainstanceRequirementsAcceleratorCountAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ac.ref.InternalTokens()
}

func (ac DatainstanceRequirementsAcceleratorCountAttributes) Max() terra.NumberValue {
	return terra.ReferenceAsNumber(ac.ref.Append("max"))
}

func (ac DatainstanceRequirementsAcceleratorCountAttributes) Min() terra.NumberValue {
	return terra.ReferenceAsNumber(ac.ref.Append("min"))
}

type DatainstanceRequirementsAcceleratorTotalMemoryMibAttributes struct {
	ref terra.Reference
}

func (atmm DatainstanceRequirementsAcceleratorTotalMemoryMibAttributes) InternalRef() (terra.Reference, error) {
	return atmm.ref, nil
}

func (atmm DatainstanceRequirementsAcceleratorTotalMemoryMibAttributes) InternalWithRef(ref terra.Reference) DatainstanceRequirementsAcceleratorTotalMemoryMibAttributes {
	return DatainstanceRequirementsAcceleratorTotalMemoryMibAttributes{ref: ref}
}

func (atmm DatainstanceRequirementsAcceleratorTotalMemoryMibAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return atmm.ref.InternalTokens()
}

func (atmm DatainstanceRequirementsAcceleratorTotalMemoryMibAttributes) Max() terra.NumberValue {
	return terra.ReferenceAsNumber(atmm.ref.Append("max"))
}

func (atmm DatainstanceRequirementsAcceleratorTotalMemoryMibAttributes) Min() terra.NumberValue {
	return terra.ReferenceAsNumber(atmm.ref.Append("min"))
}

type DatainstanceRequirementsBaselineEbsBandwidthMbpsAttributes struct {
	ref terra.Reference
}

func (bebm DatainstanceRequirementsBaselineEbsBandwidthMbpsAttributes) InternalRef() (terra.Reference, error) {
	return bebm.ref, nil
}

func (bebm DatainstanceRequirementsBaselineEbsBandwidthMbpsAttributes) InternalWithRef(ref terra.Reference) DatainstanceRequirementsBaselineEbsBandwidthMbpsAttributes {
	return DatainstanceRequirementsBaselineEbsBandwidthMbpsAttributes{ref: ref}
}

func (bebm DatainstanceRequirementsBaselineEbsBandwidthMbpsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return bebm.ref.InternalTokens()
}

func (bebm DatainstanceRequirementsBaselineEbsBandwidthMbpsAttributes) Max() terra.NumberValue {
	return terra.ReferenceAsNumber(bebm.ref.Append("max"))
}

func (bebm DatainstanceRequirementsBaselineEbsBandwidthMbpsAttributes) Min() terra.NumberValue {
	return terra.ReferenceAsNumber(bebm.ref.Append("min"))
}

type DatainstanceRequirementsMemoryGibPerVcpuAttributes struct {
	ref terra.Reference
}

func (mgpv DatainstanceRequirementsMemoryGibPerVcpuAttributes) InternalRef() (terra.Reference, error) {
	return mgpv.ref, nil
}

func (mgpv DatainstanceRequirementsMemoryGibPerVcpuAttributes) InternalWithRef(ref terra.Reference) DatainstanceRequirementsMemoryGibPerVcpuAttributes {
	return DatainstanceRequirementsMemoryGibPerVcpuAttributes{ref: ref}
}

func (mgpv DatainstanceRequirementsMemoryGibPerVcpuAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return mgpv.ref.InternalTokens()
}

func (mgpv DatainstanceRequirementsMemoryGibPerVcpuAttributes) Max() terra.NumberValue {
	return terra.ReferenceAsNumber(mgpv.ref.Append("max"))
}

func (mgpv DatainstanceRequirementsMemoryGibPerVcpuAttributes) Min() terra.NumberValue {
	return terra.ReferenceAsNumber(mgpv.ref.Append("min"))
}

type DatainstanceRequirementsMemoryMibAttributes struct {
	ref terra.Reference
}

func (mm DatainstanceRequirementsMemoryMibAttributes) InternalRef() (terra.Reference, error) {
	return mm.ref, nil
}

func (mm DatainstanceRequirementsMemoryMibAttributes) InternalWithRef(ref terra.Reference) DatainstanceRequirementsMemoryMibAttributes {
	return DatainstanceRequirementsMemoryMibAttributes{ref: ref}
}

func (mm DatainstanceRequirementsMemoryMibAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return mm.ref.InternalTokens()
}

func (mm DatainstanceRequirementsMemoryMibAttributes) Max() terra.NumberValue {
	return terra.ReferenceAsNumber(mm.ref.Append("max"))
}

func (mm DatainstanceRequirementsMemoryMibAttributes) Min() terra.NumberValue {
	return terra.ReferenceAsNumber(mm.ref.Append("min"))
}

type DatainstanceRequirementsNetworkBandwidthGbpsAttributes struct {
	ref terra.Reference
}

func (nbg DatainstanceRequirementsNetworkBandwidthGbpsAttributes) InternalRef() (terra.Reference, error) {
	return nbg.ref, nil
}

func (nbg DatainstanceRequirementsNetworkBandwidthGbpsAttributes) InternalWithRef(ref terra.Reference) DatainstanceRequirementsNetworkBandwidthGbpsAttributes {
	return DatainstanceRequirementsNetworkBandwidthGbpsAttributes{ref: ref}
}

func (nbg DatainstanceRequirementsNetworkBandwidthGbpsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return nbg.ref.InternalTokens()
}

func (nbg DatainstanceRequirementsNetworkBandwidthGbpsAttributes) Max() terra.NumberValue {
	return terra.ReferenceAsNumber(nbg.ref.Append("max"))
}

func (nbg DatainstanceRequirementsNetworkBandwidthGbpsAttributes) Min() terra.NumberValue {
	return terra.ReferenceAsNumber(nbg.ref.Append("min"))
}

type DatainstanceRequirementsNetworkInterfaceCountAttributes struct {
	ref terra.Reference
}

func (nic DatainstanceRequirementsNetworkInterfaceCountAttributes) InternalRef() (terra.Reference, error) {
	return nic.ref, nil
}

func (nic DatainstanceRequirementsNetworkInterfaceCountAttributes) InternalWithRef(ref terra.Reference) DatainstanceRequirementsNetworkInterfaceCountAttributes {
	return DatainstanceRequirementsNetworkInterfaceCountAttributes{ref: ref}
}

func (nic DatainstanceRequirementsNetworkInterfaceCountAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return nic.ref.InternalTokens()
}

func (nic DatainstanceRequirementsNetworkInterfaceCountAttributes) Max() terra.NumberValue {
	return terra.ReferenceAsNumber(nic.ref.Append("max"))
}

func (nic DatainstanceRequirementsNetworkInterfaceCountAttributes) Min() terra.NumberValue {
	return terra.ReferenceAsNumber(nic.ref.Append("min"))
}

type DatainstanceRequirementsTotalLocalStorageGbAttributes struct {
	ref terra.Reference
}

func (tlsg DatainstanceRequirementsTotalLocalStorageGbAttributes) InternalRef() (terra.Reference, error) {
	return tlsg.ref, nil
}

func (tlsg DatainstanceRequirementsTotalLocalStorageGbAttributes) InternalWithRef(ref terra.Reference) DatainstanceRequirementsTotalLocalStorageGbAttributes {
	return DatainstanceRequirementsTotalLocalStorageGbAttributes{ref: ref}
}

func (tlsg DatainstanceRequirementsTotalLocalStorageGbAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return tlsg.ref.InternalTokens()
}

func (tlsg DatainstanceRequirementsTotalLocalStorageGbAttributes) Max() terra.NumberValue {
	return terra.ReferenceAsNumber(tlsg.ref.Append("max"))
}

func (tlsg DatainstanceRequirementsTotalLocalStorageGbAttributes) Min() terra.NumberValue {
	return terra.ReferenceAsNumber(tlsg.ref.Append("min"))
}

type DatainstanceRequirementsVcpuCountAttributes struct {
	ref terra.Reference
}

func (vc DatainstanceRequirementsVcpuCountAttributes) InternalRef() (terra.Reference, error) {
	return vc.ref, nil
}

func (vc DatainstanceRequirementsVcpuCountAttributes) InternalWithRef(ref terra.Reference) DatainstanceRequirementsVcpuCountAttributes {
	return DatainstanceRequirementsVcpuCountAttributes{ref: ref}
}

func (vc DatainstanceRequirementsVcpuCountAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return vc.ref.InternalTokens()
}

func (vc DatainstanceRequirementsVcpuCountAttributes) Max() terra.NumberValue {
	return terra.ReferenceAsNumber(vc.ref.Append("max"))
}

func (vc DatainstanceRequirementsVcpuCountAttributes) Min() terra.NumberValue {
	return terra.ReferenceAsNumber(vc.ref.Append("min"))
}

type DatalicenseSpecificationAttributes struct {
	ref terra.Reference
}

func (ls DatalicenseSpecificationAttributes) InternalRef() (terra.Reference, error) {
	return ls.ref, nil
}

func (ls DatalicenseSpecificationAttributes) InternalWithRef(ref terra.Reference) DatalicenseSpecificationAttributes {
	return DatalicenseSpecificationAttributes{ref: ref}
}

func (ls DatalicenseSpecificationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ls.ref.InternalTokens()
}

func (ls DatalicenseSpecificationAttributes) LicenseConfigurationArn() terra.StringValue {
	return terra.ReferenceAsString(ls.ref.Append("license_configuration_arn"))
}

type DatamaintenanceOptionsAttributes struct {
	ref terra.Reference
}

func (mo DatamaintenanceOptionsAttributes) InternalRef() (terra.Reference, error) {
	return mo.ref, nil
}

func (mo DatamaintenanceOptionsAttributes) InternalWithRef(ref terra.Reference) DatamaintenanceOptionsAttributes {
	return DatamaintenanceOptionsAttributes{ref: ref}
}

func (mo DatamaintenanceOptionsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return mo.ref.InternalTokens()
}

func (mo DatamaintenanceOptionsAttributes) AutoRecovery() terra.StringValue {
	return terra.ReferenceAsString(mo.ref.Append("auto_recovery"))
}

type DatametadataOptionsAttributes struct {
	ref terra.Reference
}

func (mo DatametadataOptionsAttributes) InternalRef() (terra.Reference, error) {
	return mo.ref, nil
}

func (mo DatametadataOptionsAttributes) InternalWithRef(ref terra.Reference) DatametadataOptionsAttributes {
	return DatametadataOptionsAttributes{ref: ref}
}

func (mo DatametadataOptionsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return mo.ref.InternalTokens()
}

func (mo DatametadataOptionsAttributes) HttpEndpoint() terra.StringValue {
	return terra.ReferenceAsString(mo.ref.Append("http_endpoint"))
}

func (mo DatametadataOptionsAttributes) HttpProtocolIpv6() terra.StringValue {
	return terra.ReferenceAsString(mo.ref.Append("http_protocol_ipv6"))
}

func (mo DatametadataOptionsAttributes) HttpPutResponseHopLimit() terra.NumberValue {
	return terra.ReferenceAsNumber(mo.ref.Append("http_put_response_hop_limit"))
}

func (mo DatametadataOptionsAttributes) HttpTokens() terra.StringValue {
	return terra.ReferenceAsString(mo.ref.Append("http_tokens"))
}

func (mo DatametadataOptionsAttributes) InstanceMetadataTags() terra.StringValue {
	return terra.ReferenceAsString(mo.ref.Append("instance_metadata_tags"))
}

type DatamonitoringAttributes struct {
	ref terra.Reference
}

func (m DatamonitoringAttributes) InternalRef() (terra.Reference, error) {
	return m.ref, nil
}

func (m DatamonitoringAttributes) InternalWithRef(ref terra.Reference) DatamonitoringAttributes {
	return DatamonitoringAttributes{ref: ref}
}

func (m DatamonitoringAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return m.ref.InternalTokens()
}

func (m DatamonitoringAttributes) Enabled() terra.BoolValue {
	return terra.ReferenceAsBool(m.ref.Append("enabled"))
}

type DatanetworkInterfacesAttributes struct {
	ref terra.Reference
}

func (ni DatanetworkInterfacesAttributes) InternalRef() (terra.Reference, error) {
	return ni.ref, nil
}

func (ni DatanetworkInterfacesAttributes) InternalWithRef(ref terra.Reference) DatanetworkInterfacesAttributes {
	return DatanetworkInterfacesAttributes{ref: ref}
}

func (ni DatanetworkInterfacesAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ni.ref.InternalTokens()
}

func (ni DatanetworkInterfacesAttributes) AssociateCarrierIpAddress() terra.StringValue {
	return terra.ReferenceAsString(ni.ref.Append("associate_carrier_ip_address"))
}

func (ni DatanetworkInterfacesAttributes) AssociatePublicIpAddress() terra.StringValue {
	return terra.ReferenceAsString(ni.ref.Append("associate_public_ip_address"))
}

func (ni DatanetworkInterfacesAttributes) DeleteOnTermination() terra.StringValue {
	return terra.ReferenceAsString(ni.ref.Append("delete_on_termination"))
}

func (ni DatanetworkInterfacesAttributes) Description() terra.StringValue {
	return terra.ReferenceAsString(ni.ref.Append("description"))
}

func (ni DatanetworkInterfacesAttributes) DeviceIndex() terra.NumberValue {
	return terra.ReferenceAsNumber(ni.ref.Append("device_index"))
}

func (ni DatanetworkInterfacesAttributes) InterfaceType() terra.StringValue {
	return terra.ReferenceAsString(ni.ref.Append("interface_type"))
}

func (ni DatanetworkInterfacesAttributes) Ipv4AddressCount() terra.NumberValue {
	return terra.ReferenceAsNumber(ni.ref.Append("ipv4_address_count"))
}

func (ni DatanetworkInterfacesAttributes) Ipv4Addresses() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](ni.ref.Append("ipv4_addresses"))
}

func (ni DatanetworkInterfacesAttributes) Ipv4PrefixCount() terra.NumberValue {
	return terra.ReferenceAsNumber(ni.ref.Append("ipv4_prefix_count"))
}

func (ni DatanetworkInterfacesAttributes) Ipv4Prefixes() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](ni.ref.Append("ipv4_prefixes"))
}

func (ni DatanetworkInterfacesAttributes) Ipv6AddressCount() terra.NumberValue {
	return terra.ReferenceAsNumber(ni.ref.Append("ipv6_address_count"))
}

func (ni DatanetworkInterfacesAttributes) Ipv6Addresses() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](ni.ref.Append("ipv6_addresses"))
}

func (ni DatanetworkInterfacesAttributes) Ipv6PrefixCount() terra.NumberValue {
	return terra.ReferenceAsNumber(ni.ref.Append("ipv6_prefix_count"))
}

func (ni DatanetworkInterfacesAttributes) Ipv6Prefixes() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](ni.ref.Append("ipv6_prefixes"))
}

func (ni DatanetworkInterfacesAttributes) NetworkCardIndex() terra.NumberValue {
	return terra.ReferenceAsNumber(ni.ref.Append("network_card_index"))
}

func (ni DatanetworkInterfacesAttributes) NetworkInterfaceId() terra.StringValue {
	return terra.ReferenceAsString(ni.ref.Append("network_interface_id"))
}

func (ni DatanetworkInterfacesAttributes) PrivateIpAddress() terra.StringValue {
	return terra.ReferenceAsString(ni.ref.Append("private_ip_address"))
}

func (ni DatanetworkInterfacesAttributes) SecurityGroups() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](ni.ref.Append("security_groups"))
}

func (ni DatanetworkInterfacesAttributes) SubnetId() terra.StringValue {
	return terra.ReferenceAsString(ni.ref.Append("subnet_id"))
}

type DataplacementAttributes struct {
	ref terra.Reference
}

func (p DataplacementAttributes) InternalRef() (terra.Reference, error) {
	return p.ref, nil
}

func (p DataplacementAttributes) InternalWithRef(ref terra.Reference) DataplacementAttributes {
	return DataplacementAttributes{ref: ref}
}

func (p DataplacementAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return p.ref.InternalTokens()
}

func (p DataplacementAttributes) Affinity() terra.StringValue {
	return terra.ReferenceAsString(p.ref.Append("affinity"))
}

func (p DataplacementAttributes) AvailabilityZone() terra.StringValue {
	return terra.ReferenceAsString(p.ref.Append("availability_zone"))
}

func (p DataplacementAttributes) GroupName() terra.StringValue {
	return terra.ReferenceAsString(p.ref.Append("group_name"))
}

func (p DataplacementAttributes) HostId() terra.StringValue {
	return terra.ReferenceAsString(p.ref.Append("host_id"))
}

func (p DataplacementAttributes) HostResourceGroupArn() terra.StringValue {
	return terra.ReferenceAsString(p.ref.Append("host_resource_group_arn"))
}

func (p DataplacementAttributes) PartitionNumber() terra.NumberValue {
	return terra.ReferenceAsNumber(p.ref.Append("partition_number"))
}

func (p DataplacementAttributes) SpreadDomain() terra.StringValue {
	return terra.ReferenceAsString(p.ref.Append("spread_domain"))
}

func (p DataplacementAttributes) Tenancy() terra.StringValue {
	return terra.ReferenceAsString(p.ref.Append("tenancy"))
}

type DataprivateDnsNameOptionsAttributes struct {
	ref terra.Reference
}

func (pdno DataprivateDnsNameOptionsAttributes) InternalRef() (terra.Reference, error) {
	return pdno.ref, nil
}

func (pdno DataprivateDnsNameOptionsAttributes) InternalWithRef(ref terra.Reference) DataprivateDnsNameOptionsAttributes {
	return DataprivateDnsNameOptionsAttributes{ref: ref}
}

func (pdno DataprivateDnsNameOptionsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return pdno.ref.InternalTokens()
}

func (pdno DataprivateDnsNameOptionsAttributes) EnableResourceNameDnsARecord() terra.BoolValue {
	return terra.ReferenceAsBool(pdno.ref.Append("enable_resource_name_dns_a_record"))
}

func (pdno DataprivateDnsNameOptionsAttributes) EnableResourceNameDnsAaaaRecord() terra.BoolValue {
	return terra.ReferenceAsBool(pdno.ref.Append("enable_resource_name_dns_aaaa_record"))
}

func (pdno DataprivateDnsNameOptionsAttributes) HostnameType() terra.StringValue {
	return terra.ReferenceAsString(pdno.ref.Append("hostname_type"))
}

type DatatagSpecificationsAttributes struct {
	ref terra.Reference
}

func (ts DatatagSpecificationsAttributes) InternalRef() (terra.Reference, error) {
	return ts.ref, nil
}

func (ts DatatagSpecificationsAttributes) InternalWithRef(ref terra.Reference) DatatagSpecificationsAttributes {
	return DatatagSpecificationsAttributes{ref: ref}
}

func (ts DatatagSpecificationsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ts.ref.InternalTokens()
}

func (ts DatatagSpecificationsAttributes) ResourceType() terra.StringValue {
	return terra.ReferenceAsString(ts.ref.Append("resource_type"))
}

func (ts DatatagSpecificationsAttributes) Tags() terra.MapValue[terra.StringValue] {
	return terra.ReferenceAsMap[terra.StringValue](ts.ref.Append("tags"))
}

type DatafilterAttributes struct {
	ref terra.Reference
}

func (f DatafilterAttributes) InternalRef() (terra.Reference, error) {
	return f.ref, nil
}

func (f DatafilterAttributes) InternalWithRef(ref terra.Reference) DatafilterAttributes {
	return DatafilterAttributes{ref: ref}
}

func (f DatafilterAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return f.ref.InternalTokens()
}

func (f DatafilterAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(f.ref.Append("name"))
}

func (f DatafilterAttributes) Values() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](f.ref.Append("values"))
}

type DatatimeoutsAttributes struct {
	ref terra.Reference
}

func (t DatatimeoutsAttributes) InternalRef() (terra.Reference, error) {
	return t.ref, nil
}

func (t DatatimeoutsAttributes) InternalWithRef(ref terra.Reference) DatatimeoutsAttributes {
	return DatatimeoutsAttributes{ref: ref}
}

func (t DatatimeoutsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return t.ref.InternalTokens()
}

func (t DatatimeoutsAttributes) Read() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("read"))
}

type DataBlockDeviceMappingsState struct {
	DeviceName  string                            `json:"device_name"`
	NoDevice    string                            `json:"no_device"`
	VirtualName string                            `json:"virtual_name"`
	Ebs         []DataBlockDeviceMappingsEbsState `json:"ebs"`
}

type DataBlockDeviceMappingsEbsState struct {
	DeleteOnTermination string  `json:"delete_on_termination"`
	Encrypted           string  `json:"encrypted"`
	Iops                float64 `json:"iops"`
	KmsKeyId            string  `json:"kms_key_id"`
	SnapshotId          string  `json:"snapshot_id"`
	Throughput          float64 `json:"throughput"`
	VolumeSize          float64 `json:"volume_size"`
	VolumeType          string  `json:"volume_type"`
}

type DataCapacityReservationSpecificationState struct {
	CapacityReservationPreference string                                                               `json:"capacity_reservation_preference"`
	CapacityReservationTarget     []DataCapacityReservationSpecificationCapacityReservationTargetState `json:"capacity_reservation_target"`
}

type DataCapacityReservationSpecificationCapacityReservationTargetState struct {
	CapacityReservationId               string `json:"capacity_reservation_id"`
	CapacityReservationResourceGroupArn string `json:"capacity_reservation_resource_group_arn"`
}

type DataCpuOptionsState struct {
	AmdSevSnp      string  `json:"amd_sev_snp"`
	CoreCount      float64 `json:"core_count"`
	ThreadsPerCore float64 `json:"threads_per_core"`
}

type DataCreditSpecificationState struct {
	CpuCredits string `json:"cpu_credits"`
}

type DataElasticGpuSpecificationsState struct {
	Type string `json:"type"`
}

type DataElasticInferenceAcceleratorState struct {
	Type string `json:"type"`
}

type DataEnclaveOptionsState struct {
	Enabled bool `json:"enabled"`
}

type DataHibernationOptionsState struct {
	Configured bool `json:"configured"`
}

type DataIamInstanceProfileState struct {
	Arn  string `json:"arn"`
	Name string `json:"name"`
}

type DataInstanceMarketOptionsState struct {
	MarketType  string                                      `json:"market_type"`
	SpotOptions []DataInstanceMarketOptionsSpotOptionsState `json:"spot_options"`
}

type DataInstanceMarketOptionsSpotOptionsState struct {
	BlockDurationMinutes         float64 `json:"block_duration_minutes"`
	InstanceInterruptionBehavior string  `json:"instance_interruption_behavior"`
	MaxPrice                     string  `json:"max_price"`
	SpotInstanceType             string  `json:"spot_instance_type"`
	ValidUntil                   string  `json:"valid_until"`
}

type DataInstanceRequirementsState struct {
	AcceleratorManufacturers                  []string                                                 `json:"accelerator_manufacturers"`
	AcceleratorNames                          []string                                                 `json:"accelerator_names"`
	AcceleratorTypes                          []string                                                 `json:"accelerator_types"`
	AllowedInstanceTypes                      []string                                                 `json:"allowed_instance_types"`
	BareMetal                                 string                                                   `json:"bare_metal"`
	BurstablePerformance                      string                                                   `json:"burstable_performance"`
	CpuManufacturers                          []string                                                 `json:"cpu_manufacturers"`
	ExcludedInstanceTypes                     []string                                                 `json:"excluded_instance_types"`
	InstanceGenerations                       []string                                                 `json:"instance_generations"`
	LocalStorage                              string                                                   `json:"local_storage"`
	LocalStorageTypes                         []string                                                 `json:"local_storage_types"`
	OnDemandMaxPricePercentageOverLowestPrice float64                                                  `json:"on_demand_max_price_percentage_over_lowest_price"`
	RequireHibernateSupport                   bool                                                     `json:"require_hibernate_support"`
	SpotMaxPricePercentageOverLowestPrice     float64                                                  `json:"spot_max_price_percentage_over_lowest_price"`
	AcceleratorCount                          []DataInstanceRequirementsAcceleratorCountState          `json:"accelerator_count"`
	AcceleratorTotalMemoryMib                 []DataInstanceRequirementsAcceleratorTotalMemoryMibState `json:"accelerator_total_memory_mib"`
	BaselineEbsBandwidthMbps                  []DataInstanceRequirementsBaselineEbsBandwidthMbpsState  `json:"baseline_ebs_bandwidth_mbps"`
	MemoryGibPerVcpu                          []DataInstanceRequirementsMemoryGibPerVcpuState          `json:"memory_gib_per_vcpu"`
	MemoryMib                                 []DataInstanceRequirementsMemoryMibState                 `json:"memory_mib"`
	NetworkBandwidthGbps                      []DataInstanceRequirementsNetworkBandwidthGbpsState      `json:"network_bandwidth_gbps"`
	NetworkInterfaceCount                     []DataInstanceRequirementsNetworkInterfaceCountState     `json:"network_interface_count"`
	TotalLocalStorageGb                       []DataInstanceRequirementsTotalLocalStorageGbState       `json:"total_local_storage_gb"`
	VcpuCount                                 []DataInstanceRequirementsVcpuCountState                 `json:"vcpu_count"`
}

type DataInstanceRequirementsAcceleratorCountState struct {
	Max float64 `json:"max"`
	Min float64 `json:"min"`
}

type DataInstanceRequirementsAcceleratorTotalMemoryMibState struct {
	Max float64 `json:"max"`
	Min float64 `json:"min"`
}

type DataInstanceRequirementsBaselineEbsBandwidthMbpsState struct {
	Max float64 `json:"max"`
	Min float64 `json:"min"`
}

type DataInstanceRequirementsMemoryGibPerVcpuState struct {
	Max float64 `json:"max"`
	Min float64 `json:"min"`
}

type DataInstanceRequirementsMemoryMibState struct {
	Max float64 `json:"max"`
	Min float64 `json:"min"`
}

type DataInstanceRequirementsNetworkBandwidthGbpsState struct {
	Max float64 `json:"max"`
	Min float64 `json:"min"`
}

type DataInstanceRequirementsNetworkInterfaceCountState struct {
	Max float64 `json:"max"`
	Min float64 `json:"min"`
}

type DataInstanceRequirementsTotalLocalStorageGbState struct {
	Max float64 `json:"max"`
	Min float64 `json:"min"`
}

type DataInstanceRequirementsVcpuCountState struct {
	Max float64 `json:"max"`
	Min float64 `json:"min"`
}

type DataLicenseSpecificationState struct {
	LicenseConfigurationArn string `json:"license_configuration_arn"`
}

type DataMaintenanceOptionsState struct {
	AutoRecovery string `json:"auto_recovery"`
}

type DataMetadataOptionsState struct {
	HttpEndpoint            string  `json:"http_endpoint"`
	HttpProtocolIpv6        string  `json:"http_protocol_ipv6"`
	HttpPutResponseHopLimit float64 `json:"http_put_response_hop_limit"`
	HttpTokens              string  `json:"http_tokens"`
	InstanceMetadataTags    string  `json:"instance_metadata_tags"`
}

type DataMonitoringState struct {
	Enabled bool `json:"enabled"`
}

type DataNetworkInterfacesState struct {
	AssociateCarrierIpAddress string   `json:"associate_carrier_ip_address"`
	AssociatePublicIpAddress  string   `json:"associate_public_ip_address"`
	DeleteOnTermination       string   `json:"delete_on_termination"`
	Description               string   `json:"description"`
	DeviceIndex               float64  `json:"device_index"`
	InterfaceType             string   `json:"interface_type"`
	Ipv4AddressCount          float64  `json:"ipv4_address_count"`
	Ipv4Addresses             []string `json:"ipv4_addresses"`
	Ipv4PrefixCount           float64  `json:"ipv4_prefix_count"`
	Ipv4Prefixes              []string `json:"ipv4_prefixes"`
	Ipv6AddressCount          float64  `json:"ipv6_address_count"`
	Ipv6Addresses             []string `json:"ipv6_addresses"`
	Ipv6PrefixCount           float64  `json:"ipv6_prefix_count"`
	Ipv6Prefixes              []string `json:"ipv6_prefixes"`
	NetworkCardIndex          float64  `json:"network_card_index"`
	NetworkInterfaceId        string   `json:"network_interface_id"`
	PrivateIpAddress          string   `json:"private_ip_address"`
	SecurityGroups            []string `json:"security_groups"`
	SubnetId                  string   `json:"subnet_id"`
}

type DataPlacementState struct {
	Affinity             string  `json:"affinity"`
	AvailabilityZone     string  `json:"availability_zone"`
	GroupName            string  `json:"group_name"`
	HostId               string  `json:"host_id"`
	HostResourceGroupArn string  `json:"host_resource_group_arn"`
	PartitionNumber      float64 `json:"partition_number"`
	SpreadDomain         string  `json:"spread_domain"`
	Tenancy              string  `json:"tenancy"`
}

type DataPrivateDnsNameOptionsState struct {
	EnableResourceNameDnsARecord    bool   `json:"enable_resource_name_dns_a_record"`
	EnableResourceNameDnsAaaaRecord bool   `json:"enable_resource_name_dns_aaaa_record"`
	HostnameType                    string `json:"hostname_type"`
}

type DataTagSpecificationsState struct {
	ResourceType string            `json:"resource_type"`
	Tags         map[string]string `json:"tags"`
}

type DataFilterState struct {
	Name   string   `json:"name"`
	Values []string `json:"values"`
}

type DataTimeoutsState struct {
	Read string `json:"read"`
}
