// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_s3_bucket_logging

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type TargetGrant struct {
	// Permission is required.
	Permission terra.StringValue `hcl:"permission,attr" validate:"required"`
	// TargetGrantGrantee is required.
	Grantee *TargetGrantGrantee `hcl:"grantee,block" validate:"required"`
}

type TargetGrantGrantee struct {
	// EmailAddress is optional.
	EmailAddress terra.StringValue `hcl:"email_address,attr"`
	// Id is optional.
	Id terra.StringValue `hcl:"id,attr"`
	// Type is required.
	Type terra.StringValue `hcl:"type,attr" validate:"required"`
	// Uri is optional.
	Uri terra.StringValue `hcl:"uri,attr"`
}

type targetGrantAttributes struct {
	ref terra.Reference
}

func (tg targetGrantAttributes) InternalRef() (terra.Reference, error) {
	return tg.ref, nil
}

func (tg targetGrantAttributes) InternalWithRef(ref terra.Reference) targetGrantAttributes {
	return targetGrantAttributes{ref: ref}
}

func (tg targetGrantAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return tg.ref.InternalTokens()
}

func (tg targetGrantAttributes) Permission() terra.StringValue {
	return terra.ReferenceAsString(tg.ref.Append("permission"))
}

func (tg targetGrantAttributes) Grantee() terra.ListValue[targetGrantGranteeAttributes] {
	return terra.ReferenceAsList[targetGrantGranteeAttributes](tg.ref.Append("grantee"))
}

type targetGrantGranteeAttributes struct {
	ref terra.Reference
}

func (g targetGrantGranteeAttributes) InternalRef() (terra.Reference, error) {
	return g.ref, nil
}

func (g targetGrantGranteeAttributes) InternalWithRef(ref terra.Reference) targetGrantGranteeAttributes {
	return targetGrantGranteeAttributes{ref: ref}
}

func (g targetGrantGranteeAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return g.ref.InternalTokens()
}

func (g targetGrantGranteeAttributes) DisplayName() terra.StringValue {
	return terra.ReferenceAsString(g.ref.Append("display_name"))
}

func (g targetGrantGranteeAttributes) EmailAddress() terra.StringValue {
	return terra.ReferenceAsString(g.ref.Append("email_address"))
}

func (g targetGrantGranteeAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(g.ref.Append("id"))
}

func (g targetGrantGranteeAttributes) Type() terra.StringValue {
	return terra.ReferenceAsString(g.ref.Append("type"))
}

func (g targetGrantGranteeAttributes) Uri() terra.StringValue {
	return terra.ReferenceAsString(g.ref.Append("uri"))
}

type TargetGrantState struct {
	Permission string                    `json:"permission"`
	Grantee    []TargetGrantGranteeState `json:"grantee"`
}

type TargetGrantGranteeState struct {
	DisplayName  string `json:"display_name"`
	EmailAddress string `json:"email_address"`
	Id           string `json:"id"`
	Type         string `json:"type"`
	Uri          string `json:"uri"`
}
