// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_networkmanager_device

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type AwsLocation struct {
	// SubnetArn is optional.
	SubnetArn terra.StringValue `hcl:"subnet_arn,attr"`
	// Zone is optional.
	Zone terra.StringValue `hcl:"zone,attr"`
}

type Location struct {
	// Address is optional.
	Address terra.StringValue `hcl:"address,attr"`
	// Latitude is optional.
	Latitude terra.StringValue `hcl:"latitude,attr"`
	// Longitude is optional.
	Longitude terra.StringValue `hcl:"longitude,attr"`
}

type Timeouts struct {
	// Create is optional.
	Create terra.StringValue `hcl:"create,attr"`
	// Delete is optional.
	Delete terra.StringValue `hcl:"delete,attr"`
	// Update is optional.
	Update terra.StringValue `hcl:"update,attr"`
}

type awsLocationAttributes struct {
	ref terra.Reference
}

func (al awsLocationAttributes) InternalRef() (terra.Reference, error) {
	return al.ref, nil
}

func (al awsLocationAttributes) InternalWithRef(ref terra.Reference) awsLocationAttributes {
	return awsLocationAttributes{ref: ref}
}

func (al awsLocationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return al.ref.InternalTokens()
}

func (al awsLocationAttributes) SubnetArn() terra.StringValue {
	return terra.ReferenceAsString(al.ref.Append("subnet_arn"))
}

func (al awsLocationAttributes) Zone() terra.StringValue {
	return terra.ReferenceAsString(al.ref.Append("zone"))
}

type locationAttributes struct {
	ref terra.Reference
}

func (l locationAttributes) InternalRef() (terra.Reference, error) {
	return l.ref, nil
}

func (l locationAttributes) InternalWithRef(ref terra.Reference) locationAttributes {
	return locationAttributes{ref: ref}
}

func (l locationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return l.ref.InternalTokens()
}

func (l locationAttributes) Address() terra.StringValue {
	return terra.ReferenceAsString(l.ref.Append("address"))
}

func (l locationAttributes) Latitude() terra.StringValue {
	return terra.ReferenceAsString(l.ref.Append("latitude"))
}

func (l locationAttributes) Longitude() terra.StringValue {
	return terra.ReferenceAsString(l.ref.Append("longitude"))
}

type timeoutsAttributes struct {
	ref terra.Reference
}

func (t timeoutsAttributes) InternalRef() (terra.Reference, error) {
	return t.ref, nil
}

func (t timeoutsAttributes) InternalWithRef(ref terra.Reference) timeoutsAttributes {
	return timeoutsAttributes{ref: ref}
}

func (t timeoutsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return t.ref.InternalTokens()
}

func (t timeoutsAttributes) Create() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("create"))
}

func (t timeoutsAttributes) Delete() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("delete"))
}

func (t timeoutsAttributes) Update() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("update"))
}

type AwsLocationState struct {
	SubnetArn string `json:"subnet_arn"`
	Zone      string `json:"zone"`
}

type LocationState struct {
	Address   string `json:"address"`
	Latitude  string `json:"latitude"`
	Longitude string `json:"longitude"`
}

type TimeoutsState struct {
	Create string `json:"create"`
	Delete string `json:"delete"`
	Update string `json:"update"`
}
