// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_s3control_object_lambda_access_point

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type Configuration struct {
	// AllowedFeatures is optional.
	AllowedFeatures terra.SetValue[terra.StringValue] `hcl:"allowed_features,attr"`
	// CloudWatchMetricsEnabled is optional.
	CloudWatchMetricsEnabled terra.BoolValue `hcl:"cloud_watch_metrics_enabled,attr"`
	// SupportingAccessPoint is required.
	SupportingAccessPoint terra.StringValue `hcl:"supporting_access_point,attr" validate:"required"`
	// ConfigurationTransformationConfiguration is min=1.
	TransformationConfiguration []ConfigurationTransformationConfiguration `hcl:"transformation_configuration,block" validate:"min=1"`
}

type ConfigurationTransformationConfiguration struct {
	// Actions is required.
	Actions terra.SetValue[terra.StringValue] `hcl:"actions,attr" validate:"required"`
	// ConfigurationTransformationConfigurationContentTransformation is required.
	ContentTransformation *ConfigurationTransformationConfigurationContentTransformation `hcl:"content_transformation,block" validate:"required"`
}

type ConfigurationTransformationConfigurationContentTransformation struct {
	// ConfigurationTransformationConfigurationContentTransformationAwsLambda is required.
	AwsLambda *ConfigurationTransformationConfigurationContentTransformationAwsLambda `hcl:"aws_lambda,block" validate:"required"`
}

type ConfigurationTransformationConfigurationContentTransformationAwsLambda struct {
	// FunctionArn is required.
	FunctionArn terra.StringValue `hcl:"function_arn,attr" validate:"required"`
	// FunctionPayload is optional.
	FunctionPayload terra.StringValue `hcl:"function_payload,attr"`
}

type configurationAttributes struct {
	ref terra.Reference
}

func (c configurationAttributes) InternalRef() (terra.Reference, error) {
	return c.ref, nil
}

func (c configurationAttributes) InternalWithRef(ref terra.Reference) configurationAttributes {
	return configurationAttributes{ref: ref}
}

func (c configurationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return c.ref.InternalTokens()
}

func (c configurationAttributes) AllowedFeatures() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](c.ref.Append("allowed_features"))
}

func (c configurationAttributes) CloudWatchMetricsEnabled() terra.BoolValue {
	return terra.ReferenceAsBool(c.ref.Append("cloud_watch_metrics_enabled"))
}

func (c configurationAttributes) SupportingAccessPoint() terra.StringValue {
	return terra.ReferenceAsString(c.ref.Append("supporting_access_point"))
}

func (c configurationAttributes) TransformationConfiguration() terra.SetValue[configurationTransformationConfigurationAttributes] {
	return terra.ReferenceAsSet[configurationTransformationConfigurationAttributes](c.ref.Append("transformation_configuration"))
}

type configurationTransformationConfigurationAttributes struct {
	ref terra.Reference
}

func (tc configurationTransformationConfigurationAttributes) InternalRef() (terra.Reference, error) {
	return tc.ref, nil
}

func (tc configurationTransformationConfigurationAttributes) InternalWithRef(ref terra.Reference) configurationTransformationConfigurationAttributes {
	return configurationTransformationConfigurationAttributes{ref: ref}
}

func (tc configurationTransformationConfigurationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return tc.ref.InternalTokens()
}

func (tc configurationTransformationConfigurationAttributes) Actions() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](tc.ref.Append("actions"))
}

func (tc configurationTransformationConfigurationAttributes) ContentTransformation() terra.ListValue[configurationTransformationConfigurationContentTransformationAttributes] {
	return terra.ReferenceAsList[configurationTransformationConfigurationContentTransformationAttributes](tc.ref.Append("content_transformation"))
}

type configurationTransformationConfigurationContentTransformationAttributes struct {
	ref terra.Reference
}

func (ct configurationTransformationConfigurationContentTransformationAttributes) InternalRef() (terra.Reference, error) {
	return ct.ref, nil
}

func (ct configurationTransformationConfigurationContentTransformationAttributes) InternalWithRef(ref terra.Reference) configurationTransformationConfigurationContentTransformationAttributes {
	return configurationTransformationConfigurationContentTransformationAttributes{ref: ref}
}

func (ct configurationTransformationConfigurationContentTransformationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ct.ref.InternalTokens()
}

func (ct configurationTransformationConfigurationContentTransformationAttributes) AwsLambda() terra.ListValue[configurationTransformationConfigurationContentTransformationAwsLambdaAttributes] {
	return terra.ReferenceAsList[configurationTransformationConfigurationContentTransformationAwsLambdaAttributes](ct.ref.Append("aws_lambda"))
}

type configurationTransformationConfigurationContentTransformationAwsLambdaAttributes struct {
	ref terra.Reference
}

func (al configurationTransformationConfigurationContentTransformationAwsLambdaAttributes) InternalRef() (terra.Reference, error) {
	return al.ref, nil
}

func (al configurationTransformationConfigurationContentTransformationAwsLambdaAttributes) InternalWithRef(ref terra.Reference) configurationTransformationConfigurationContentTransformationAwsLambdaAttributes {
	return configurationTransformationConfigurationContentTransformationAwsLambdaAttributes{ref: ref}
}

func (al configurationTransformationConfigurationContentTransformationAwsLambdaAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return al.ref.InternalTokens()
}

func (al configurationTransformationConfigurationContentTransformationAwsLambdaAttributes) FunctionArn() terra.StringValue {
	return terra.ReferenceAsString(al.ref.Append("function_arn"))
}

func (al configurationTransformationConfigurationContentTransformationAwsLambdaAttributes) FunctionPayload() terra.StringValue {
	return terra.ReferenceAsString(al.ref.Append("function_payload"))
}

type ConfigurationState struct {
	AllowedFeatures             []string                                        `json:"allowed_features"`
	CloudWatchMetricsEnabled    bool                                            `json:"cloud_watch_metrics_enabled"`
	SupportingAccessPoint       string                                          `json:"supporting_access_point"`
	TransformationConfiguration []ConfigurationTransformationConfigurationState `json:"transformation_configuration"`
}

type ConfigurationTransformationConfigurationState struct {
	Actions               []string                                                             `json:"actions"`
	ContentTransformation []ConfigurationTransformationConfigurationContentTransformationState `json:"content_transformation"`
}

type ConfigurationTransformationConfigurationContentTransformationState struct {
	AwsLambda []ConfigurationTransformationConfigurationContentTransformationAwsLambdaState `json:"aws_lambda"`
}

type ConfigurationTransformationConfigurationContentTransformationAwsLambdaState struct {
	FunctionArn     string `json:"function_arn"`
	FunctionPayload string `json:"function_payload"`
}
