// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_s3outposts_endpoint

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type networkInterfacesAttributes struct {
	ref terra.Reference
}

func (ni networkInterfacesAttributes) InternalRef() (terra.Reference, error) {
	return ni.ref, nil
}

func (ni networkInterfacesAttributes) InternalWithRef(ref terra.Reference) networkInterfacesAttributes {
	return networkInterfacesAttributes{ref: ref}
}

func (ni networkInterfacesAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ni.ref.InternalTokens()
}

func (ni networkInterfacesAttributes) NetworkInterfaceId() terra.StringValue {
	return terra.ReferenceAsString(ni.ref.Append("network_interface_id"))
}

type NetworkInterfacesState struct {
	NetworkInterfaceId string `json:"network_interface_id"`
}
