// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_lambda_function

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type DatadeadLetterConfigAttributes struct {
	ref terra.Reference
}

func (dlc DatadeadLetterConfigAttributes) InternalRef() (terra.Reference, error) {
	return dlc.ref, nil
}

func (dlc DatadeadLetterConfigAttributes) InternalWithRef(ref terra.Reference) DatadeadLetterConfigAttributes {
	return DatadeadLetterConfigAttributes{ref: ref}
}

func (dlc DatadeadLetterConfigAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return dlc.ref.InternalTokens()
}

func (dlc DatadeadLetterConfigAttributes) TargetArn() terra.StringValue {
	return terra.ReferenceAsString(dlc.ref.Append("target_arn"))
}

type DataenvironmentAttributes struct {
	ref terra.Reference
}

func (e DataenvironmentAttributes) InternalRef() (terra.Reference, error) {
	return e.ref, nil
}

func (e DataenvironmentAttributes) InternalWithRef(ref terra.Reference) DataenvironmentAttributes {
	return DataenvironmentAttributes{ref: ref}
}

func (e DataenvironmentAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return e.ref.InternalTokens()
}

func (e DataenvironmentAttributes) Variables() terra.MapValue[terra.StringValue] {
	return terra.ReferenceAsMap[terra.StringValue](e.ref.Append("variables"))
}

type DataephemeralStorageAttributes struct {
	ref terra.Reference
}

func (es DataephemeralStorageAttributes) InternalRef() (terra.Reference, error) {
	return es.ref, nil
}

func (es DataephemeralStorageAttributes) InternalWithRef(ref terra.Reference) DataephemeralStorageAttributes {
	return DataephemeralStorageAttributes{ref: ref}
}

func (es DataephemeralStorageAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return es.ref.InternalTokens()
}

func (es DataephemeralStorageAttributes) Size() terra.NumberValue {
	return terra.ReferenceAsNumber(es.ref.Append("size"))
}

type DatafileSystemConfigAttributes struct {
	ref terra.Reference
}

func (fsc DatafileSystemConfigAttributes) InternalRef() (terra.Reference, error) {
	return fsc.ref, nil
}

func (fsc DatafileSystemConfigAttributes) InternalWithRef(ref terra.Reference) DatafileSystemConfigAttributes {
	return DatafileSystemConfigAttributes{ref: ref}
}

func (fsc DatafileSystemConfigAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return fsc.ref.InternalTokens()
}

func (fsc DatafileSystemConfigAttributes) Arn() terra.StringValue {
	return terra.ReferenceAsString(fsc.ref.Append("arn"))
}

func (fsc DatafileSystemConfigAttributes) LocalMountPath() terra.StringValue {
	return terra.ReferenceAsString(fsc.ref.Append("local_mount_path"))
}

type DatatracingConfigAttributes struct {
	ref terra.Reference
}

func (tc DatatracingConfigAttributes) InternalRef() (terra.Reference, error) {
	return tc.ref, nil
}

func (tc DatatracingConfigAttributes) InternalWithRef(ref terra.Reference) DatatracingConfigAttributes {
	return DatatracingConfigAttributes{ref: ref}
}

func (tc DatatracingConfigAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return tc.ref.InternalTokens()
}

func (tc DatatracingConfigAttributes) Mode() terra.StringValue {
	return terra.ReferenceAsString(tc.ref.Append("mode"))
}

type DatavpcConfigAttributes struct {
	ref terra.Reference
}

func (vc DatavpcConfigAttributes) InternalRef() (terra.Reference, error) {
	return vc.ref, nil
}

func (vc DatavpcConfigAttributes) InternalWithRef(ref terra.Reference) DatavpcConfigAttributes {
	return DatavpcConfigAttributes{ref: ref}
}

func (vc DatavpcConfigAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return vc.ref.InternalTokens()
}

func (vc DatavpcConfigAttributes) SecurityGroupIds() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](vc.ref.Append("security_group_ids"))
}

func (vc DatavpcConfigAttributes) SubnetIds() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](vc.ref.Append("subnet_ids"))
}

func (vc DatavpcConfigAttributes) VpcId() terra.StringValue {
	return terra.ReferenceAsString(vc.ref.Append("vpc_id"))
}

type DataDeadLetterConfigState struct {
	TargetArn string `json:"target_arn"`
}

type DataEnvironmentState struct {
	Variables map[string]string `json:"variables"`
}

type DataEphemeralStorageState struct {
	Size float64 `json:"size"`
}

type DataFileSystemConfigState struct {
	Arn            string `json:"arn"`
	LocalMountPath string `json:"local_mount_path"`
}

type DataTracingConfigState struct {
	Mode string `json:"mode"`
}

type DataVpcConfigState struct {
	SecurityGroupIds []string `json:"security_group_ids"`
	SubnetIds        []string `json:"subnet_ids"`
	VpcId            string   `json:"vpc_id"`
}
