// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_gamelift_game_server_group

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type AutoScalingPolicy struct {
	// EstimatedInstanceWarmup is optional.
	EstimatedInstanceWarmup terra.NumberValue `hcl:"estimated_instance_warmup,attr"`
	// AutoScalingPolicyTargetTrackingConfiguration is required.
	TargetTrackingConfiguration *AutoScalingPolicyTargetTrackingConfiguration `hcl:"target_tracking_configuration,block" validate:"required"`
}

type AutoScalingPolicyTargetTrackingConfiguration struct {
	// TargetValue is required.
	TargetValue terra.NumberValue `hcl:"target_value,attr" validate:"required"`
}

type InstanceDefinition struct {
	// InstanceType is required.
	InstanceType terra.StringValue `hcl:"instance_type,attr" validate:"required"`
	// WeightedCapacity is optional.
	WeightedCapacity terra.StringValue `hcl:"weighted_capacity,attr"`
}

type LaunchTemplate struct {
	// Id is optional.
	Id terra.StringValue `hcl:"id,attr"`
	// Name is optional.
	Name terra.StringValue `hcl:"name,attr"`
	// Version is optional.
	Version terra.StringValue `hcl:"version,attr"`
}

type Timeouts struct {
	// Create is optional.
	Create terra.StringValue `hcl:"create,attr"`
	// Delete is optional.
	Delete terra.StringValue `hcl:"delete,attr"`
}

type autoScalingPolicyAttributes struct {
	ref terra.Reference
}

func (asp autoScalingPolicyAttributes) InternalRef() (terra.Reference, error) {
	return asp.ref, nil
}

func (asp autoScalingPolicyAttributes) InternalWithRef(ref terra.Reference) autoScalingPolicyAttributes {
	return autoScalingPolicyAttributes{ref: ref}
}

func (asp autoScalingPolicyAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return asp.ref.InternalTokens()
}

func (asp autoScalingPolicyAttributes) EstimatedInstanceWarmup() terra.NumberValue {
	return terra.ReferenceAsNumber(asp.ref.Append("estimated_instance_warmup"))
}

func (asp autoScalingPolicyAttributes) TargetTrackingConfiguration() terra.ListValue[autoScalingPolicyTargetTrackingConfigurationAttributes] {
	return terra.ReferenceAsList[autoScalingPolicyTargetTrackingConfigurationAttributes](asp.ref.Append("target_tracking_configuration"))
}

type autoScalingPolicyTargetTrackingConfigurationAttributes struct {
	ref terra.Reference
}

func (ttc autoScalingPolicyTargetTrackingConfigurationAttributes) InternalRef() (terra.Reference, error) {
	return ttc.ref, nil
}

func (ttc autoScalingPolicyTargetTrackingConfigurationAttributes) InternalWithRef(ref terra.Reference) autoScalingPolicyTargetTrackingConfigurationAttributes {
	return autoScalingPolicyTargetTrackingConfigurationAttributes{ref: ref}
}

func (ttc autoScalingPolicyTargetTrackingConfigurationAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ttc.ref.InternalTokens()
}

func (ttc autoScalingPolicyTargetTrackingConfigurationAttributes) TargetValue() terra.NumberValue {
	return terra.ReferenceAsNumber(ttc.ref.Append("target_value"))
}

type instanceDefinitionAttributes struct {
	ref terra.Reference
}

func (id instanceDefinitionAttributes) InternalRef() (terra.Reference, error) {
	return id.ref, nil
}

func (id instanceDefinitionAttributes) InternalWithRef(ref terra.Reference) instanceDefinitionAttributes {
	return instanceDefinitionAttributes{ref: ref}
}

func (id instanceDefinitionAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return id.ref.InternalTokens()
}

func (id instanceDefinitionAttributes) InstanceType() terra.StringValue {
	return terra.ReferenceAsString(id.ref.Append("instance_type"))
}

func (id instanceDefinitionAttributes) WeightedCapacity() terra.StringValue {
	return terra.ReferenceAsString(id.ref.Append("weighted_capacity"))
}

type launchTemplateAttributes struct {
	ref terra.Reference
}

func (lt launchTemplateAttributes) InternalRef() (terra.Reference, error) {
	return lt.ref, nil
}

func (lt launchTemplateAttributes) InternalWithRef(ref terra.Reference) launchTemplateAttributes {
	return launchTemplateAttributes{ref: ref}
}

func (lt launchTemplateAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return lt.ref.InternalTokens()
}

func (lt launchTemplateAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(lt.ref.Append("id"))
}

func (lt launchTemplateAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(lt.ref.Append("name"))
}

func (lt launchTemplateAttributes) Version() terra.StringValue {
	return terra.ReferenceAsString(lt.ref.Append("version"))
}

type timeoutsAttributes struct {
	ref terra.Reference
}

func (t timeoutsAttributes) InternalRef() (terra.Reference, error) {
	return t.ref, nil
}

func (t timeoutsAttributes) InternalWithRef(ref terra.Reference) timeoutsAttributes {
	return timeoutsAttributes{ref: ref}
}

func (t timeoutsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return t.ref.InternalTokens()
}

func (t timeoutsAttributes) Create() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("create"))
}

func (t timeoutsAttributes) Delete() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("delete"))
}

type AutoScalingPolicyState struct {
	EstimatedInstanceWarmup     float64                                             `json:"estimated_instance_warmup"`
	TargetTrackingConfiguration []AutoScalingPolicyTargetTrackingConfigurationState `json:"target_tracking_configuration"`
}

type AutoScalingPolicyTargetTrackingConfigurationState struct {
	TargetValue float64 `json:"target_value"`
}

type InstanceDefinitionState struct {
	InstanceType     string `json:"instance_type"`
	WeightedCapacity string `json:"weighted_capacity"`
}

type LaunchTemplateState struct {
	Id      string `json:"id"`
	Name    string `json:"name"`
	Version string `json:"version"`
}

type TimeoutsState struct {
	Create string `json:"create"`
	Delete string `json:"delete"`
}
