// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_route53recoverycontrolconfig_safety_rule

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type RuleConfig struct {
	// Inverted is required.
	Inverted terra.BoolValue `hcl:"inverted,attr" validate:"required"`
	// Threshold is required.
	Threshold terra.NumberValue `hcl:"threshold,attr" validate:"required"`
	// Type is required.
	Type terra.StringValue `hcl:"type,attr" validate:"required"`
}

type ruleConfigAttributes struct {
	ref terra.Reference
}

func (rc ruleConfigAttributes) InternalRef() (terra.Reference, error) {
	return rc.ref, nil
}

func (rc ruleConfigAttributes) InternalWithRef(ref terra.Reference) ruleConfigAttributes {
	return ruleConfigAttributes{ref: ref}
}

func (rc ruleConfigAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return rc.ref.InternalTokens()
}

func (rc ruleConfigAttributes) Inverted() terra.BoolValue {
	return terra.ReferenceAsBool(rc.ref.Append("inverted"))
}

func (rc ruleConfigAttributes) Threshold() terra.NumberValue {
	return terra.ReferenceAsNumber(rc.ref.Append("threshold"))
}

func (rc ruleConfigAttributes) Type() terra.StringValue {
	return terra.ReferenceAsString(rc.ref.Append("type"))
}

type RuleConfigState struct {
	Inverted  bool    `json:"inverted"`
	Threshold float64 `json:"threshold"`
	Type      string  `json:"type"`
}
